owntone/owntone-server

- INSTALL
- README.md
- configure.ac
- sqlext/sqlext.c
- src/Makefile.am
- src/conffile.c
- src/db.c
- src/db.h
- src/filescanner.c
- src/filescanner.h
- src/filescanner_itunes.c
- src/filescanner_playlist.c
- src/httpd_dacp.c
- src/logger.c
- src/logger.h
- src/main.c
- src/mpd.c
- src/mpd.h
- src/player.c
- src/player.h
- src/spotify.c
It is in a very early stage, but I started working on the support for the mpd protocol (see #51).
By now forked-daapd excepts connections from mpd clients (on port 8800) and returns static responses for "status" and "currentsong". For all other commands it returns an error.
@ejurgensen it would be great if you could have a look at the approach i have taken. Any feedback welcome!
> [wip] mpd protocol

- src/filescanner_itunes.c
- src/main.c
@ejurgensen these two commits should fix the problems you mentioned in #107.
> Fix compile error & warning

- src/httpd_dacp.c
This is an attempt at improving the selection of a song from the "previously played" list. 
Remote sends the command "playnow" with mode "-1" if an entry of the history was selected. The index parameter is then the position of this entry in the history queue. Currently the mode parameter is not taken into account and therefor issuing this action results in playing the song from the "up next" queue at the position identified by the index parameter.
With these changes if mode is "-1", forked-daapd will look in the history to identify the song to start playing.
If the song is found and it is also present in the playqueue, forked-daapd will skip back to this song in the playqueue (gets the song id from the history and starts playing this id).
What is not working after these changes is, that …
> Improve behaviour for playing from history

- src/db.c
A db upgrade can take very long and in case of an error leaves the db in an invalid state (partially updated). This can be improved by doing the update in a single transaction. If an error during the update occurs the whole changes will be rolled back. 
The performance gain depends on the number of queries that are executed during the update. In case of the upgrade from 15.1 to 16.0, this is quite significant as each row in the files and playlist table is updated.
Because of the update being part of the db init, db locking is not an issue (there are no other threads that will access the db during the initialization).
> Enclose DB upgrade in a single transaction 

- src/mpd.c
This pr implements support for the mpd commands to control speakers (outputs). 
Following commands are supported:
* disableoutput
* enableoutput
* toggleoutput
Sadly the existing speaker (raop) id can not be used, as it is to large for mpd. I introduced a "num" for each speaker, that gets simply incremented if a new speaker gets added to the device list.
The mpd protocol only allows to activate or deactivate a speaker (output), setting volume for a specific speaker is not supported.
> [mpd] add support for speaker (de)activation 

- src/mpd.c
This is the pr for the patch provided by Ravio Hool. Thanks for reporting and fixing it!
> [mpd] fix compile error on FreeBSD (thanks to Raivo Hool)

- src/db.c
- src/db.h
- src/mpd.c
First commit adds support for the "count" command of the mpd protocol. Support for this command is e. g. necessary for listing albums of an artist in MPDroid. 
Second commit fixes the "list" command for albumartists.
> [mpd] support for "count" command and fix for listing albumartists

- src/player.c
> Fix first item is not random

- README_SMARTPL.md
- src/SMARTPL.g
> [smartpl] add "grouping" field to smart playlist grammar

- src/queue.c
Added missing check if there are not items to add to the queue
> [queue] fix segfault if query for queue-items returned an empty result

- src/mpd.c
- src/player.c
- src/queue.c
> Some fixes for the mpd protocol support

- src/mpd.c
- src/player.c
- src/player.h
This makes the "Add and replace" from the MPDroid context menu work correctly
> [mpd] implement range support for 'delete' command

- src/mpd.c
@ejurgensen could please check if this change solves the seek issue you have? I did not remove the check for the current playing song, but instead fixed the comparison (similar to how it is done for seekid). 
In the second commit i fixed an error in the status command.
> [mpd] Fix seek command

- src/mpd.c
> [mpd] Add missing close for command pipe on deinit

- src/cache.c
- src/db.c
- src/db.h
- src/spotify.c
cached artwork for removed spotify songs
> [spotify/artwork] Remove spotify songs after playlist update and delete

- src/mpd.c
@LordMyschkin noticed in the log (i think from using cantata) that support for the command plchangesposid from the mpd protocol is missing. This pr implements it, by reporting all songs in the queue as changed (similar to the command plchanges).
> [mpd] Implement command 'plchangesposid'

- src/queue.c
Removes duplicate code for the different move-methods and fixes moving an item to the end of the queue (resulted in an error message that an invalid position was given).
> [queue] Fix moving a song to the last position in the queue failed

- src/spotify.c
I ran into an edge case by following to playlists from spotify with the same name ("Rock im Park 2016"). Due to the same name their virtual path are identical and mpd clients are not able to list the songs from the playlist.
This pr works around this issue by appending the owner to the virtual path:
spotify:/Rock im Park 2016 (rockimparkofficial)
spotify:/Rock im Park 2016 (theres_no_cake)
> [spotify] Add the owner of playlist to the virtual path

- src/Makefile.am
- src/cache.c
- src/commands.c
- src/commands.h
- src/filescanner.c
- src/mpd.c
- src/player.c
- src/spotify.c
- src/worker.c
Hi @ejurgensen,
as shortly discussed via mail, this pr introduces a generic helper for communicating between threads running a libevent eventloop. Especially the changes in player.c need a thorough review.
> Refactor inter thread communication

- src/httpd_dacp.c
- src/mdns_avahi.c
First commit fixes a compile warning, second sets the correct logdomain in some log messags in httpd_dacp.c
> Minor cleanup

- src/db.c
- src/db.h
> [db] Small code improvements (avoid hard coded values in query strings)

- src/RSP2SQL.g
- src/mpd.c
- src/queue.c
Fixes issues reported by scan-build in mpd.c, queue.c and RSP2SQL.c (see #312)
> Fix issues found by scanbuild

- src/db.c
- src/db.h
- src/db_init.c
- src/db_init.h
- src/db_upgrade.c
- src/lastfm.c
A little cleanup that unfortunately requires a (minor) db upgrade. Hope i have done it right this time ...
> Add primary key column to admin table

- src/db.c
- src/httpd_dacp.c
- src/player.c
- src/spotify_webapi.c
- src/spotify_webapi.h
This should address your comments on #331.
scan-build reported some issues in player/dacp/db which are also addressed by this pr.
> Fix memory leaks / scan-build issues

- src/spotify.c
The existing setting for 'artist_override' and 'album_override' are currently ignored, if the scan happens with the spotify webapi. This pr changes this. The override happens only for tracks that are not in a saved album.
> [spotify] Respect settings for 'artist_override' and 'album_override'

- configure.ac
- src/Makefile.am
- src/mdns_avahi.c
- src/mdns_dnssd.c
- src/misc.c
- src/misc.h
- src/outputs/cast.c
- src/outputs/raop.c
These patches include the missing high resolution timers and direct Bonjour support, and the necessary configuration changes needed to compile/run on OSX.  I've only done limited testing, but everything appears to work at first glance.  This is a branch off of fixthreads, so it includes all those changes too.
> OSX patches

- INSTALL
- scripts/antlr35_install.sh
I've added detailed instructions on installing macports and other requirements on OSX, and
tried it out on a spare laptop.
Also minor fix to antlr3_install.sh for OSX :)
> Added OSX macports install instructions

- src/httpd_dacp.c
@ejurgensen this should fix the problem with starting playback of an album with shuffle active.
> [dacp] Always start playing from the beginning of the shuffle queue

- src/db.c
- src/db.h
- src/mpd.c
> [mpd] Fix wrong db playime info in 'stats' command

- src/outputs/raop.c
- src/player.c
Hi Espen, just some small changes i made against your "playback_resilience" branch, to help debugging/testing my playback issues. Might be useful if someone else runs into problems. Feel free to cherry pick the changes you like.
> Playback resilience

- src/library/filescanner.c
> Missing break statement?

- src/inputs/pipe.c
Hi Espen, 
This is a little addition to the pipe input to support instant volume changes by reading the desired volume off the metadata pipe and adjusting the player_volume.
Shairport sync forwards volume changes immediately via "pvol" metadata items and I've added the necessary code in `pipe.c:parse_volume(*char)` (similar to parse_progress()) to support them.
With this PR volume changes are instant and not delayed by several seconds. In addition it also ensures that there's only a single volume to care about and that audio data is not resampled to match a volume which can have a negative impact on the quality.
In order to avoid that the source (shairport-sync) applies software volume control this change requires that shairport-sync is configured with `ignore_volume_control = "yes"`. As …
> Add support for instant volume changes when using metadata pipe (pvol)

- src/mpd.c
> [mpd] password command

- src/httpd.c
- src/httpd.h
- src/mpd.c
This is a tested working solution. Please, move the utilities to the appropriate places.
> [mpd] apply trusted_networks to MPD

- src/db.c
- src/db.h
- src/lastfm.c
- src/library.c
- src/mpd.c
- src/spotify_webapi.c
@ejurgensen commit b062760a5b4590d3b17e6a023ae5dc463d3f53a3 fixes a mistake i made in the last pr, resulting in the noidle command returning an error (this can subsequently lead to a segfault). If i should make a separate pr for this, please let me know.
> MPD fixes and support 'uptime' in stats command

- src/mpd.c
@chme It is a bit annoying having to kill my telnet session manually and reset the terminal when debugging/testing.
> [mpd] Close connection for close command

- src/http.c
Support for .pls playlists.
I'm not so sure about the arbitrary limit of 10 lines? It should not be a problem to scan 100 lines or 1000.
Maybe at least skip all blank and comment lines without counting them.
> [http] .pls playlists

- htdocs/admin.html
- htdocs/js/forked-daapd.js
- src/httpd_dacp.c
- src/httpd_jsonapi.c
- src/listener.h
- src/mpd.c
- src/outputs/raop.c
- src/player.c
- src/player.h
- src/websocket.c
@ejurgensen i followed your advice to put a callback into the player to trigger the outputs update event. I think this is complete now, but have no way to test it.
> Integrate device verification into the web interface

- src/cache.c
- src/db.c
- src/db.h
- src/httpd_dacp.c
- src/library.c
- src/library.h
- src/listener.h
- src/mpd.c
> Support "rating" sticker

- htdocs/Makefile.am
- src/Makefile.am
Just a few modifications to some Makefile.am's so that make distcheck works (and make dist creates a complete tarfile :)
> [configure] Fixed make distcheck

- src/httpd_dacp.c
- src/httpd_jsonapi.c
- src/mpd.c
- src/player.c
- src/player.h
No functional change, just some refactoring to make it easier to enable/disable a single output (see change in mpd.c).
> Refactore output enumeration and support enable/disable of single output

- README_JSON_API.md
- htdocs/js/forked-daapd.js
- src/httpd.c
- src/httpd.h
- src/httpd_jsonapi.c
- src/misc_json.c
- src/misc_json.h
* Adds a new endpoint to enable/disable and/or change volume of an output
* Checks for the correct request method for all endpoints (GET to read data, POST/PUT for changes)
* And an initial documentation of the api endpoints (README_JSON_API.md)
> JSON api cleanup and documentation

- src/db.c
- src/mpd.c
Added a commit fixing some function comments in db.c
> Fix compiler warnings

- README_SMARTPL.md
> Fixed typo

- src/db.c
- src/db.h
- src/httpd_dacp.c
... and remove an unused function.
> Add missing transaction end in error case

- README_SMARTPL.md
- src/SMARTPL.g
- src/SMARTPL2SQL.g
Add "starts with" to smart playlist language. Fixes #491
> [smartpl] Add "starts with" to smart playlist language

- README.md
> [README] Add link to JSON API documentation

- INSTALL
It is not simple to fix build warnings from antlr3.
For now, document them so users know they are safe to ignore.
> Added documentation about harmless warnings to INSTALL file.

- README_SMARTPL.md
- src/SMARTPL.g
I wanted to order the tracks in a smart playlist by disc and track. With this PR this is possible.
> Add support for track and disc items in smart playlists

- src/player.c
Fix for https://github.com/chme/forked-daapd-web/issues/4
> [player] Send notification on output added/removed

- src/httpd_jsonapi.c
Fix error in web interface files-view if the library directory end with a trailing slash.
Reported on the rpi-forum: https://www.raspberrypi.org/forums/viewtopic.php?p=1421358#p1421358
> [jsonapi] Fix error in web interface files-view

- src/SMARTPL2SQL.g
> Fix smart playlist queries for date fields compared with "before"

- src/library/filescanner.c
- web-src/src/components/ModalDialogAddUrlStream.vue
- web-src/src/pages/PageQueue.vue
enable support for add `https` streams to library
> [library] accept https:// streams

- src/httpd_jsonapi.c
Alternative for #750 
@ejurgensen if you have time, could you take a quick look? Will do some tests during the day and merge afterwards.
> [jsonapi] Fix segfault if no default playlist directory is set in conf

- src/SMARTPL2SQL.g
Closes https://github.com/ejurgensen/forked-daapd/issues/767
> [smartpl] use start of today (ie 00:00) for DATE calculations

- web-src/src/App.vue
- web-src/src/components/ModalDialogAlbum.vue
- web-src/src/components/NavbarItemLink.vue
- web-src/src/components/NavbarItemOutput.vue
- web-src/src/components/NavbarTop.vue
- web-src/src/pages/PageNowPlaying.vue
- web-src/src/router/index.js
- web-src/src/webapi/index.js
- keep scroll position of the current page after opening the burger menu
- fix navbar links not working if burger menu is open
- remove the arrow on the navbar dropdowns
- correctly append the maxsize parameters for local artwork urls
> Small fixes for the player web interface

- src/spotify_webapi.c
This should fix #791 by returning the first image from spotify if no max width is given.
> Fix for Remote not showing nowplaying artwork for Spotify tracks

- src/httpd_jsonapi.c
> [jsonapi] potential memleaks on query_params.filter object

- src/mpd.c
> [mpd] Fix initial value of 'songpos' in play command

- README_JSON_API.md
- src/httpd_jsonapi.c
> New JSON API endpoint for toggling outputs

- src/DAAP2SQL.g
Address #785 for Apple Music users
> Recognize '@' as an operator identical to ':'

- htdocs/admin.html
> Add link to player web interface to admin page

- src/artwork.c
I think, it is time to drop fetching artwork over libspotify. As far as i can tell, this always fails and only fetching artwork over the spotify web api works.
The second commit refactors the internal `artwork_get_dir_image` (totally unrelated), i had this sitting in a branch and imo it makes this function easier to understand.
This needs more testing, had to rebase it and resolve conflicts ... but it is good for a code review.
> Remove libspotify as artwork source + refactoring

- src/websocket.c
fixes compilation under newer musl.
> websocket: add header for errno

- README_ALSA.md
- add troubleshooting section
- clarify requirement on amixer device
- notes on using the alsa equalizer plugin
Updating to address recent ALSA queries such as #935 and on Raspberry Pi forum
> [README] updates for ALSA

- src/websocket.c
Libwebsockets sometimes generates multiple LWS_CALLBACK_CLIENT_WRITEABLE events per lws_callback_on_writable_all_protocol() call: https://libwebsockets.org/lws-api-doc-master/html/md_READMEs_README_8coding.html
In my case I was actually getting notify callbacks after every keepalive ping.
The change I made just uses an unsigned short to keep track of the notify event number and matches that against the local copy in each websocket session, not sending when they are still the same.
> Updated websocket.c to notify once per event cycle

- src/SMARTPL.g
More fields to be useful in web ui `query:` page / smartpl
> [smartpl] support song_length

- README_JSON_API.md
- README_SMARTPL.md
Updated to reflect changes #994 / #995  and examples from #992
> [README] smart pl and  json update

- README_ALSA.md
Update readme to be in-sync with #1054 to help users configure ALSA outputs using more descriptive device names.
> [README] show configuration using ALSA device aliases

- src/conffile.c
- src/db.c
- src/db.h
- src/httpd_jsonapi.c
Functionality to create db backups via REST call.
This is especially useful for systems that keep the db in memory on an overlay filesystem to reduce write to underlying persistent storage (SD card).
> Database backup

- README_JSON_API.md
- forked-daapd.conf.in
doc and config template for recent #1052 merge
> [readme] db backup

- src/spotify_webapi.c
Add support to force metadata update in the Spotify library scanner.
> [spotify] Force metadata update on library "metarescan" update

- forked-daapd.spec.in
Followup to pull request #1121 - adding comment (need new pull request as previous one already merged :)
> [spec] Add comment on reason for libplist-devel requires

- src/library/rssscanner.c
Current impl fetches pl, purge pl items, fetch RSS, inserts entries.  If the RSS
fetch fails (remote server is temporary unreachable) the playlistitems for that
RSS are all dropped.
This has a side effect that RSS playlists cannot be determined from tracks (see
issue #1126) and thus cannot be deleted.
Simple fix to defer playlist item purge to the point that the RSS fetch is ok
and before the inserts
> [rss] defer playlistitems purge til ready to update with new rss

- src/http.c
Some servers send metadata in non UTF-8 formats such as ISO-8859-1 (see charset under https://icecast.org/docs/icecast-2.4.1/config-file.html)
libav assumes UTF-8 but does not enforce it, so some of the metadata comes through as non-UTF-8.
This can result in weird behavior including incorrect character display and can also propagate downstream with improperly encoded strings getting sent through the JSON API.
For an example stream, see https://www.radioswisspop.ch/en/reception/internet . Every so often an artist or song name will have a non ASCII character that is encoded correctly in ISO-8859-1 but is invalid UTF-8. The string will be written with an incorrect encoding to the database, and the web player will not display the character correctly.
> Check utf-8 in metadata_packet_get

- src/mpd.c
I hope this change will improve the performance in the Regelian MPD client (see  https://github.com/ejurgensen/forked-daapd/issues/1158#issuecomment-761526203)
> [mpd] Support search/find/count with `modified-since` filter criteria

- src/httpd.c
Only serve files to the web front end, that are in the web root directory.
@ejurgensen As far as I can remember, the web interface is the only client that makes use of httpd.c `serve_file` function right?
> Deny access to files outside the web root directory

- htdocs/site.webmanifest
I missed one file in the web ui update ...
> [htdocs] Update site webmanifest (renaming forked-daapd to OwnTone)

- src/httpd_dacp.c
- src/outputs/airplay.c
- src/outputs/raop.c
- src/player.c
- src/player.h
> [dacp] Fix support for device-volume (speaker volume buttons)

- src/httpd.c
Fixes #1239 by implementing the solution proposed by @whatdoineed2do (https://github.com/owntone/owntone-server/issues/1239#issuecomment-865911406)
> [httpd] Dereference web root directory to allow symlinks

- src/Makefile.am
- src/outputs/airplay.c
- src/outputs/airplay_events.c
- src/outputs/airplay_events.h
> [airplay] Experimental support for airplay events (eg Homepod controls)

- src/inputs/librespot-c/src/librespot-c.c
- src/inputs/spotify.c
- src/inputs/spotify_librespotc.c
- src/library/spotify_webapi.c
* don't load library if library playback login failed
* better reset of connection after access point disconnect
* fix locking that seems not to have been working
Resolves #1317
> Fix for Spotify disconnect issues

- web-src/src/webapi/index.js
composer related paths to be relative as per 39b14ff8d
> [web-src] inline with 39b14ff8d - relative paths for proxy'ing

- README_SMARTPL.md
- src/parsers/smartpl_lexer.l
- src/parsers/smartpl_parser.y
Simple keyword mirror `last week` etc.
Been in my own branch for a long time, somehow never pushed for PR.
> [smartpl] add 'THIS WEEK'

- src/db.c
> [db] fix 'add next' when in queue shuffle mode

- src/db.c
- src/parsers/smartpl_parser.y
- src/smartpl_query.c
> [db] Fix incorrect sorting of album/artist searches via web api

- owntone.conf.in
- src/conffile.c
- src/library.c
> [library] Move clear_queue_on_stop_disable cfg option to library section

- src/websocket.c
> [web] typo prevent handling of LISTENER_SPEAKER events

- docs/smart-playlists.md
- src/db.c
- src/db.h
- src/httpd_jsonapi.c
- src/parsers/smartpl_lexer.l
Incl `file_size` in the `COUNT` query and expose on REST and smartpl
> [db,jsonapi,smartpl] add `file_size` to count query and expose on smartpl

- src/inputs/librespot-c/README.md
- src/inputs/librespot-c/src/connection.c
- src/inputs/librespot-c/tests/test1.c
- src/inputs/spotify_librespotc.c
> [spotify] Fix for "Premium account required"

- src/player.c
As reported by @LordMyschkin having cosume mode and repeat mode both turned on does not make sense.
This PR implements the suggested solution:
- Turning consume mode on now turns repeat mode off
- Turning repeat mode on now turns consume mode off
Fixes #1478
> [player] Turn repeat mode off when activating consume mode

- web-src/src/locales/en.json
- web-src/src/locales/fr.json
- web-src/src/pages/SettingsPageOnlineServices.vue
> [web] Remove inexistent property use_libspotity #1492

- scripts/freebsd_install.sh
• Allow script to run as root without sudo installed.
• Easier setup of custom username and group (aligned with 'media' across my jails)
• Easier setup of custom configuration directory (aligned with /config fstab entry in my jails to make jail rebuild without configuration loss easier)
• Small change to allow building with clang on aarch64 due to testing in a FreeBSD VM on top of macOS
> Improvements for FreeBSD installation

- docs/advanced/outputs-pulse.md
> Fix typo: "runnning"

- web-src/src/i18n.js
- web-src/src/locales/de.json
First try for a Pull Request to add german language to owntone und to finally enable language suppot in i18n.js
> German translation

- web-src/src/components/ListDirectories.vue
- web-src/src/components/ModalDialogDirectory.vue
- web-src/src/pages/PageFiles.vue
> [web] directory modal handling fix

- web-src/src/components/ModalDialogQueueItem.vue
- web-src/src/filter/index.js
- web-src/src/lib/GroupByList.js
- web-src/src/locales/en.json
- web-src/src/locales/fr.json
- web-src/src/webapi/index.js
This is a fix for the error messages not displaying anymore. See #1500 for more information.
> [web] Fix for error messages not displaying #1500

- web-src/src/locales/de.json
Still found some room for improvement on the German Language file, mainly "De-anglification" plurals of Playlist and a fistful of typos.
> [web-ui] Minor improvements to german translation

- web-src/src/locales/de.json
- web-src/src/locales/en.json
- web-src/src/locales/fr.json
Again, I noticed a few translations mistakes.
Some translations couldn't be displayed because of a wrongly written key.
Thanks for including this in the next release.
> Minor translation mistakes

- src/library/filescanner.c
> [scan] Handles dupl db entry on file overwrite/move/replace within library

- owntone.conf.in
- src/conffile.c
- src/outputs/raop.c
> [raop] Make compressed ALAC default, but with a config option

- docs/json-api.md
Fix broken link about smart playlist query expression
> [Docs] Fix smart-playlist link

- .github/workflows/macos_12.yml
This proposed change streamlines the CI pipeline for macOS 12 and macOS latest.
> [ci] Streamline macOS pipelines

- web-src/src/i18n/index.js
- web-src/src/i18n/zh-CN.json
- web-src/src/i18n/zh-TW.json
Introduction to traditional Chinese, it is a variation of Chinese mainly used in Taiwan, Hong Kong and overseas Chinese communities. Also change the original Chinese json file from zh.json to zh-CN.json.
> Amendement of translation and introduction of Traditional Chinese translation

- web-src/src/i18n/zh-CN.json
> [web] Improve simplified Chinese translation

- configure.ac
- src/Makefile.am
- src/library/filescanner.c
- src/library/filescanner.h
- src/library/filescanner_mountwatch.c
> [scan] Use libmount to detect filesystem mount events
