forked-daapd.conf
src/artwork.c
src/cache.c
src/cache.h
src/conffile.c

This pull request re-adds support for individual artwork, including support for caching individual artwork.
The first commit adds back basic support for individual artwork.  When a request for an individual media item's artwork is made, this logic looks first for embedded artwork and then for a jpg or png file in the same path and with the same base name as the media file. If no individual artwork is found, then it proceeds with the existing search for group artwork pertaining to the item (including a search of the cache).
The second and third commits add support for caching individual artwork.  The second commit modifies the artwork cache table and api to allow for distinguishing between individual artwork and group artwork. Because persistent ids for individual media and persistent ids …

Add back support for individual media artwork

---

src/DAAP2SQL.g
src/artwork.c
src/cache.c
src/db.c
src/db.h
src/filescanner.c

While poking around in db.c, i took a shot at further improving performance. One issue with long running select queries to the files database table for e. g. album or artist lists is, that it always joins the groups table. This is necessary to retrieve the group id (only the persistent id of the group is saved in the files table). 
This pr removes the persistent id column from the groups table and makes the group id persistent over restarts. This allows to save the group id in the files table (songartistid and songalbumid) and to eliminate the join in the select queries. The triggers for inserts and updates to the files table are replaced by an explicit select/insert to the groups table.

Improve select queries for files table

---

src/filescanner_itunes.c

I tried importing my iTunes ratings but noticed that the file path matching didn't work. With this change it works as expected including the directory matching.
Not sure why it matches "localhost" in the first. My iTunes is version 12 on OS X, but as far as I remember iTunes doesn't use "localhost" in its library since the beginning. Rather it's "file:///Users/username/Music/...."

Fix filepath matching for iTunes library import

---

src/player.c

This fixes the issue reported by @TomAlperin that the first song is not shuffled.
The queue handling is getting quite complex and is sometimes hard to follow, so i hope, i did not introduce any regression.

first song not shuffled

---

src/httpd_dacp.c

Fixes a segfault introduced with the mpd changes in the playspec dacp-command

Fix segfault when playing audiobooks

---

src/db.c
src/db.h
src/filescanner.c

The third commit should fix the segfault reported in #106. The second one should fix the full-rescan functionality and the first one fixes a copy/paste mistake i made.

Fix segfault when loading playlists

---

scripts/pairinghelper.sh

The pairing helper script didn't work for me because of two issues:
- Library Path had to be without spaces
- Log: [2015-02-26 21:00:16] [  LOG]   remote: Remote '-e remoteXX' not known from mDNS, ignoring
I tried to fix these two issues and want to share this. I hope you like it.
(This is my first pull request ever, so please tell me if I did something wrong :yum:)

Pairinghelper Fixes

---

src/player.c

The compiler complains about the unread return value of "read":
```
player.c:1807:7: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
read(fd, &ticks, sizeof(ticks));
```
I think it is good to at least write a log message, if there where no bytes read.

silence compiler warning in player.c "warning: ignoring return value"

---

sqlext/sqlext.c
src/db.c

This should fix the issues with utf8 characters when selecting from the filelist view (infinite loop in MPoD while importing the library and missing or wrong entries in ympd).
I replaced the sql extension functions i added for the mpd support with the charindexFunc and leftFunc from "extension-functions.c" published on sqlite.org "Contributed Files" (http://www.sqlite.org/contrib). I kept my modifications to the functions to a minimum (only changed the naming and the indentation).
I would appreciate if you could test, if this fixes the infinite loop in MPoD for you.

[mpd] fix issues with utf8 characters when selecting from filelist 

---

src/db.c
src/db.h
src/mpd.c
src/player.c

First commit fixes a typo, removes the wrongly added line breaks at the end of error messages and escapes the virtual path when building the query to add songs to the queue. The last one mentioned fixes sql errors if the virtual path contains a ' character.
Second commit adds support for some additional commands. I am not so sure if the db changes to add a new browse type (year) are the best way to implement this. I probably will need more of these (the mpd protocol allows this kind of browsing for all supported tags) and i am thinking if a generic method (just passing the tag/field) would be better. What do you think?

[mpd] some fixes and support for new commands

---

src/db.c
src/mpd.c

The first commit adds support for IPv6 if it is enabled in the config. The second adresses the issue you mentioned (simply renaming the data_kind variable to type and removing the data_kind column from the select query).

[mpd] add IPv6 support and a little cleanup in db upgrade v16

---

configure.ac
forked-daapd.conf
src/Makefile.am
src/conffile.c
src/laudio.c
src/laudio.h
src/laudio_alsa.c
src/laudio_dummy.c
src/laudio_oss4.c

These changes are heavily inspired by the shairport implementation for audio outputs. 
It allows to have multiple audio output implementations instead of one (alsa or oss4) that is determined at compile time. Which implementation is used by forked-daapd is configured in the forked-daapd.conf file. 
In addition to the existing implementations for alsa and oss4, i added a dummy output. 
With the changes in configure.ac it should now be possible to compile without alsa and without oss4 and to only use the dummy output.
I only tested the alsa changes and my knowledge of configure.ac is rather limited ...
What do you think @ejurgensen ?

[laudio] Make output type for local audio configurable

---

src/http.c

@ejurgensen i ran into a problem when trying to open the radio streams from deutschlandradio.de (e. g. http://www.deutschlandradio.de/streaming/dkultur.m3u). Playback did not start and the http request from forked-daapd for this uri returned 404 "page not found".
Comparing the requests from vlc to forked-daapd showed that the different values for the header value "Host" caused the problem.
Request from vlc:
```
GET /streaming/dkultur.m3u HTTP/1.1
Host: www.deutschlandradio.de
User-Agent: VLC/2.1.6 LibVLC/2.1.6
Range: bytes=0-
Connection: close
Icy-MetaData: 1
```
Request from forked-daapd:
```
GET /streaming/dkultur.m3u HTTP/1.1
Host: www.deutschlandradio.de:80
Content-Length: 0
User-Agent: forked-daapd/22.3
Icy-MetaData: 1
```
After omitting the port number ":80" in the header value, the …

Problem opening stream - error code 404

---

README_SMARTPL.md
src/db.h

This fixes the wrong media_kind value for music and some typos in the readme file for smart playlists

Fix wrong media kind value for music

---

src/cache.c
src/cache.h
src/filescanner.c

see title, this also contains the change of the DPRINTF for size_t from %d to %zu

do not execute individual delete queries for cached artwork files during bulk scan

---

README.md
src/mpd.c

While updating the readme section for mpd clients, i noticed that the following command does not work:
```
mpc list artist
```
The second commit fixes this.

Fix mpd command "list" for artists and readme updates

---

src/DAAP2SQL.g
src/cache.c

First commit fixes the query parsing for daap requests for music videos (media-kind 32). 
Second commit deletes cache entries, if the rebuild of the cache failed (this could happen if a smart playlist was cached and afterwards delete).

Fix log warning for incorrect daap query

---

src/mpd.c

Running the mpd command "listplaylists" segfaults on master. This is because the pl-type was hardcoded into the query-filter. I missed changing it, when doing the changes to the pl_type enum.

Segfault running mpd command "listplaylists"

---

src/db.c
src/db.h
src/mpd.c
src/player.c
src/player.h

These commits add support for additional mpd commands (like findadd or searchadd) and improve support for some commands like find or search. See individual commit messages for details.
The change in player.c exposes the generic player_queue_make function. This allows to keep the logic for building the query in mpd.c instead of moving it to the player (like it is done for player_queue_make_daap, player_queue_make_mpd). I was not sure if it would be good to move these two methods out of the player and into the daap/mpd files, so i kept them where they are.
@ejurgensen it would be great, if you could take a look at the changes

Add support for additional mpd commands

---

src/Makefile.am
src/httpd_dacp.c
src/listener.c
src/listener.h
src/mpd.c
src/mpd.h
src/player.c
src/player.h

These commits add support for the mpd "idle" command. The idle command is used by mpd to notify clients about changes on the server. There are different notifications like database, player, ... (see full list at http://www.musicpd.org/doc/protocol/command_reference.html#status_commands).
This pr only adds the notifications that inform about changes related to player.c (play status, playlist, volume, speaker).
I wanted to avoid a compile dependencies at all these places in player.c (with the ifdef for mpd, as it is a compile time option) and added a listener/event logic. I also changed the update call for daap/dacp remotes to use this listener/event logic instead of setting a callback function.
With this pr and #149 i had some success using clients like gmpc, cantata or MPDroid (modifying …

Add support for mpd idle command

---

src/db.c
src/db.h
src/mpd.c

Some additions to improve the mpd client support:
* Report the whole playqueue in plchanges (instead of ignoring the command), this is needed for clients relying on this command to display the queue (e. g. sonata and hopefully mPad)
* Allow listing the virtual_path in list command (used in sonata during retrieval of albums for an artist)
* Support date argument in find and search commands (avoids duplicate entries in sonata for albums)
@ejurgensen please take a look especially at the change in db.h. I tried to figure out if the enum value could be extended to use 3 bytes instead of 2. What i found searching the web was that an enum has the size of an int. The size of int seems to be platform dependent, so i guess its safer to stay on 2 bytes?

Support for mpd command plchanges 

---

src/db.c
src/filescanner.c
src/http.c
src/misc.c
src/misc.h

encoded/converted. Characters above x7F were replaced by '?' character
although the rfc defines a ISO−8859−1 encoding for descriptive
field-content.
According to rfc2616 the field-content is defined as follows:
<the OCTETs making up the field-value and consisting of either *TEXT or
combinations of token, separators, and quoted-string>
The TEXT rule is only used for descriptive field contents and values
that are not intended to be interpreted by the message parser. Words of
*TEXT MAY contain characters from character sets other than ISO- 8859-1
only when encoded according to the rules of RFC 2047.
In the previous implementation the icy metadata was converted based on
fromcode "ascii".
Following incoming icy header field-values should be encoded as
"ISO−8859−1" before adding them to the …

Fixed bug that caused icy header metadata to be not correctly encoded

---

src/db.c
src/filescanner_playlist.c
src/filescanner_smartpl.c

MPD lists stored playlists without the file extension. Including the file extension (like forked-daapd currently does) leads to problems in MPDroid. The playlists are not listed correctly in the app and they cannot be added to the queue.
This pr changes the creation of the virtual path for playlists and updates the virtual path for already stored playlists in the library.
I updated the db version to v19. Would it be better to use v18.01 as the upgrade does not change the db structure?

Remove file extension for playlists from virtual_path

---

src/mpd.c

In order to retrieve the current playlist some mpd clients call the "playlistinfo" command with -1 as range argument. The first commit changes forked-daapd to return the whole queue in this case.
The second and third commit improve support for ncmpccp as a mpd client for forked-daapd and therefor implements the decoders command and changes the lsinfo command to also return the stored playlists if the root directory was passed as argument.

[mpd] some fixes to playlistinfo and lsinfo

---

forked-daapd.conf
src/conffile.c
src/db.c
src/db.h
src/mpd.c

Some MPD clients, like MPDroid or MPoD, have an option to retrieve local cover art. When using MPD as server application. This is achieved by setting up a separate http-server and pointing its document root to the MPD music directory. The cover art for a song must be an image with a defined filename, e. g. "Folder.jpg" (the name is configurable in the MPD clients), in the same directory.
I guess this could also be set up for forked-daapd, but due to the virtual path (with prefix of "file:", "spotify:", ...) would require some more knowledge of setting up a web server (some rewrite rules must be added). The drawback would be, that it would not support embedded artwork and artwork for songs from spotify.
So here is an approach of adding support for it directly in forked-daapd. I added a new …

[mpd] support serving artwork over http

---

configure.ac

Specifying --disable-* currently sets the corresponding flag enabled.  See the [Autotools Mythbuster](https://autotools.io/autoconf/arguments.html) for why that happens, specifically the Warning on the linked page and figure 1.1.
Thanks for reviewing this.  The fix is required for a Gentoo ebuild to behave in an expected way, honoring the user's desired settings.

Fix --disable-*

---

scripts/antlr35_install.sh
src/RSP.g

This involves a harmless backwards-compatible adjustment to the grammar. It is beneficial because 3.4 is broken under Java 8.

Allow ANTLR 3.5 to work and update script

---

src/httpd_dacp.c
src/player.c

First commit should fix the segfault if reading failed for all queue items, the second commit should fix starting playback of a specific item in a playlist.

Playerfixes

---

src/mpd.c
src/queue.c

The item-ids for the songs in the current playlist are wrong. The original values are overridden in queue_add and need to be restored to the original values (in ympd this leads to the error, that the current playing song is not marked as such in the playqueue).
Additionally, i corrected the log message for failing to bind to the http_port.

Fix item-id in mpd commands "playlistid", "playlistinfo", "plchanges"

---

src/player.c

Hi @ejurgensen,
before the queue/player refactoring, pausing a radio stream (or playing from a pipe) stopped playback and cleared the whole queue. This pr restores this behaviour. 
I don't really like the dependency on the data kind in the playback_pause_bh function (one of the motivations for the player refactoring was to eliminate such dependencies), but it is the non obtrusive fix for this, as far as i can see.

Restore behaviour for pause command when playing http-streams

---

src/httpd_dacp.c

@ejurgensen this fixes playing from the history from Remote for me. The mode parameter for this request seems to have changed from -1 to 1 for starting playback from the history. I checked with Retune and Retune still send the request with mode = -1.
Starting playback from the playqueue has mode = 0.

[dacp] Fix playing from history for Remote

---

src/mpd.c
src/player.c
src/player.h
src/queue.c
src/queue.h

This pr adds the ability to move songs in the playqueue for mpd clients that are using the moveid command (e. g. MPDroid). There is another move command (moving by position) that is still missing (ncmcpp is one client that makes use of it).
The implementation of the close command is merely to suppress the error log message if a client issues this command.

[mpd] Add support for moveid and close command

---

src/mpd.c

This should fix missing stored playlists in mPoD and using mpc lsplaylists command without parameter.

[mpd] Return playlists if lsinfo is called with an empty path

---

src/mpd.c
src/queue.c

First commit fixes the order in which songs are added to the queue with the mpd commands findadd and searchadd.
Second commit fixes that playback stops if the now playing item is not in the queue anymore (happens after clearing the queue).
Third commit fixes the mpd command seekid which is used by MPDroid to seek in the now playing item.

some fixes

---

src/db.c
src/db.h
src/mpd.c

Currently the stats command only returns dummy values. Besides giving information about the size of the library (number of artists, albums, songs), I noticed that mPoD seems to use the stats command for calculating the progress of the library import (probably by using the number of songs).
Still missing is the uptime, last library update time and the time played.

[mpd] Implement parts of stats command

---

src/main.c
src/mdns_avahi.c

This adds mdns announcement for the for "_mpd._tcp" to forked-daapd and makes the first connection to forked-daapd easier for mpd clients that support it (the only client i know that uses the announcement is mPod).
In the following output from avahi-browse the announcement as "Music Player" is from a running mpd server, the announcement for "music 23.3" is from forked-daapd running on my rpi:
```
$ avahi-browse -r -k _mpd._tcp
+  wlan2 IPv6 Music Player                                  _mpd._tcp            local
+  wlan2 IPv4 Music Player                                  _mpd._tcp            local
=  wlan2 IPv6 Music Player                                  _mpd._tcp            local
hostname = [studio-1749.local]
address = [fe80::fa16:54ff:fef8:9c6]
port = [6600]
txt = []
=  wlan2 IPv4 …
```

[mpd] Announce mpd support with avahi/zeroconf

---

scripts/pairinghelper.sh

Before the fix, a log entry for ‘Foo’s iPhone’ would be parsed as
originating from the device “Foo”. I have changed the matching to
include the parenthesis opening after the closing single quote.

Fix paringhelper.sh to operate correctly for device names with apostrophe

---

INSTALL
README_SMARTPL.md

INSTALL: You can't run the script before you clone the repo.  Also updated the name of the script.
Fixed typo in README_SMARTPL.md.

Fixed typos in instructions

---

src/db.c
src/db.h
src/httpd_daap.c
src/httpd_rsp.c
src/mpd.c

Hi @ejurgensen,
currently loading the playlists from the db always additionally fetches the item count for each playlist. The count query on a rpi can take quite long, especially if you have smart playlists where the count query cannot use an existing index.
The mpd commands for playlists do not use the item count information, so this pr improves performance for these queries, by skipping the item count queries.

[db] Make loading of playlistitem count optional

---

src/mpd.c
src/player.c
src/player.h
src/queue.c
src/queue.h

This pr implements the "move" command (moving items in the queue) used by MPoD. Only moving a single item is supported, if a range of items is given only the first item will be moved to the new position.

[mpd] Implement mpd command 'move'

---

forked-daapd.conf
src/conffile.c
src/spotify.c

Spotify removed the "starred" playlist and it is not possible anymore to add new songs to it.
The config options to exclude the starred songs form the artist/album override are useless now and this pr removes them.
I am not using the "artist_override" and "album_override" option anymore as it only made sense for me as long as there was a possibility to exclude songs from it. I am not sure if it would be best to completely remove them?

[spotify] Remove options to exclude starred songs from artist/album override

---

src/mpd.c

In some cases. e. g. calling lsinfo with a non existent directory path, forked-daapd segfaults due to a missing error message. The error message is necessary for building the error response.

[mpd] Fix segfault if mpd command exits with error

---

src/cache.c
src/filescanner.c
src/httpd.c
src/mpd.c
src/player.c
src/spotify.c
src/worker.c

This makes identifying the different threads a little bit easier. And fixes two todos in player (unnecessary check removed).

Set thread names

---

forked-daapd.conf
src/conffile.c
src/httpd_dacp.c
src/mpd.c
src/player.c
src/player.h
src/queue.c

This addresses #224 (commit 963f837 is not  related to this and contains two fixes for the mpd commands addid and status)
The changes allow adding songs through mpd clients without automatically starting playback, if player was stopped (commit fe9ed57). 
Having a non empty playqueue is something iTunes does not have. Therefor the support in dacp clients varies. Remote seems to work fine with this change (at least my somewhat outdated version). With commit 21b9b0d Remote shows the queue and with commits 014824f, 7160366, fc674a1, it also allows editing the queue. Retune on the other hand does not always show the queue if the player is stopped (UpNext stays empty).
The last commit 8ccac55 needs some discussion. It removes the clearing of the queue after aborting playback (e. g. after the …

Do not start playback after adding songs to the queue using mpd clients

---

src/mpd.c

see title/commit-message. Should fix #247

[mpd] Return playlists if 'lsinfo' is called without any parameters

---

src/conffile.c
src/httpd.c

Add a new general config setting allow_origin that is included as
Access-Control-Allow-Origin header in http responses. This allows to make http
request against forked-daapd from browsers with enabled CORS
(https://www.w3.org/TR/cors/) via JavaScript XMLHttpRequest.
Per default the setting is not defined and no Access-Control-Allow-Origin header
is included in the response.

Allow to add Access-Control-Allow-Origin header to responses

---

src/player.c

There is only one sync source left and therefor no need to keep the enum

[player] Cleanup: player clock is the only sync-source available

---

src/cache.c
src/commands.c
src/commands.h
src/filescanner.c
src/mpd.c
src/player.c
src/spotify.c
src/worker.c

This removes the exit pipes from the various places (e. g. player, filescanner, ...) and moves the thread exit logic to the commands util. 
@ejurgensen I hope, understood your comment regarding the naming correctly.

Refactor thread exit handling

---

src/httpd_daap.c

The content-codes url provides a mapping of dmap content codes to names, it's
types and sizes. It doesn't contain any private information and therefore should
be available to anonymous users too.

Allow anonymous access to /content-codes url

---

src/mpd.c

If musicplayer deamon is already playing, the commands 'play' and 'playid' do not pause playback but instead are ignored (if argument is -1) or are starting the given song from the beginning. This pr changes forked-daapd to react in the same way, with the exception that calling 'playid' with -1 as argument will return an error to the client instead of simply ignoring the command.

Fix behavior for mpd commands play and playid during playback

---

src/filescanner.c

Library directories with a trailing '/'  in the config file (like '/srv/music/' instead of '/srv/musc') lead to an unbrowsable directory structure. The trailing '/' resulted in an update to the library directory in the directories table with a parent_id pointing to itself.

[filescanner] Fix building directory structure with trailing '/'

---

src/commands.c
src/player.c
src/spotify.c

I hope, i found all command functions not returning COMMAND_END or COMMAND_PENDING. I also changed the behavior, if a command function does not return a valid value (see last commit).

Fix return values in command functions

---

forked-daapd.conf
src/conffile.c
src/outputs/alsa.c

Support a separate mixer_device configuration file option for
advanced ALSA configurations. Previously, ALSA local output
happened to work becasue "default" is valid as both a PCM and a
mixer. Now you can separately specify the device name for PCM
output and mixer operations.
In my setup, I am using the following:
card = "default:CARD=NVidia"
mixer = "Front"
mixer_device = "hw:CARD=NVidia"

[ALSA] Add mixer_device configuration file option for ALSA

---

src/commands.h
src/mpd.c
src/player.c

This is a nasty one ... found it because it resulted in segfaults in my persistentqueue branch. Not sure if it could result in a segfault on current master, but it is the reason why playback shortly stops while adding new songs.
The cause is, that calling playback_start can return early if player is already playing. After this early return the bottom half function should not be executed.

Fix adding items while playing through dacp clients

---

src/httpd_dacp.c
src/mpd.c
src/player.c
src/player.h

This pr extends the mpd client protocol by adding support to change volume of an individual speaker (as proposed on the mpd mailing list: http://mailman.blarg.de/pipermail/mpd-devel/2015-October/000445.html).
Speaker volume can be changed by the 'outputsvolume' command. It takes the speaker id and the volume as parameters.
Additionally the 'outputs' command reports the current volume of each speaker through an additional response line 'outputvolume: [volume]' for each speaker.
As this command is not supported by mpd, no mpd client exists that makes use of this. I tested it with a custom version of https://github.com/Mic92/python-mpd2 
This is related to the discussion in #283

[mpd] outputsvolume command

---

src/outputs/fifo.c

This is an attempt at keeping the output to the fifo in sync with the other outputs. I do not really like the introduction of yet another buffer ... but all other solutions i could come up with, would result in major changes. 
@ejurgensen if you have a better solution let me know.

Sync output to fifo

---

src/httpd.c
src/pipe.c
src/pipe.h
src/player.c
src/spotify.c
src/spotify.h
src/transcode.c
src/transcode.h

This is preliminary work to allow playing items, that are not persisted in the files table.
The different backends (transcode, spotify, pipe, httpd) don't really need a media file. Mostly the path is enough to start playback.

Reduce dependency to media file in stream setup methods

---

src/spotify.c

Without setting a virtual path the "spotify:savedtracks" playlist shows in mpd clients as "NULL)"

[spotify] Add missing virtual path to "Saved Tracks" playlist

---

src/db_upgrade.c

I messed up the db upgrade in my previous pr. The change from v20.00 to v19.01 was incomplete. 
There are two possible fixes, the one in this pr changes the db upgrade (which will lead to problems if someone already updated), another solution would be to change the db init.
This is currently untested (will do the test in the afternoon)

[db] Fix upgrade to v19.01

---

src/mpd.c
src/player.c
src/player.h

This pr adds support for the consume mode (each song played is removed from the queue). Only mpd clients support setting the consume mode.

[mpd] Add support for the 'consume' player mode

---

src/db.c
src/db.h
src/filescanner.c

Rebuilding the persistent ids for songalbum and songartist takes a noticeable amount of time (on my rpi2 it can take up to 10 seconds). The rebuild is only necessary, if the db was created on a different machine. This is - as far as i know - an undocumented feature (not sure if it actually works), that probably was a workaround for the extremely long scanning times on older versions of forked-daapd.
In favor of faster startup times, i would like to remove this feature.
If you want to keep it, it would make sense to only rebuild, if it is actually necessary. The only difference i spotted, that varies between different machines, is that there is a hash function for 32 bit and 64 bit systems. This information could be stored in the db to only rebuild if it actually changed.

Remove rebuilding the persistent-ids on startup

---

.travis.yml

It would be nice, if this could be included in master. If you do not register your github repository with travic-ci.org it should do no harm. If registered, a build is triggered and checked with scan-build automatically after each push: https://travis-ci.org/chme/forked-daapd

[travic-ci] Added configuration file for travis-ci

---

src/commands.c
src/db.c
src/logger.c
src/main.c
src/misc.c
src/misc.h
src/remote_pairing.c
src/spotify.c
src/spotify_webapi.c

I struggled with memory corruption problems on OSX for a few hours before finally tracking down some uninitialized thread structures (leading to stack corruption).  In the process of tracking this down, I added checks on all the mutex/condition calls so that the next time this happens, it'll be easier to track down!  This may also catch thread problems in code i haven't tested yet (for example, I don't have a spotify account to run checks on the library, but then they're removing support for it soon, and that's another issue :)

[threads] Added missing initializers, check errors on mutex/cond calls

---

scripts/antlr35_install.sh
scripts/pairinghelper.sh

I found myself re-using the pairing and antlr install scripts on several machines, and in various ways that they really didn't support (repeated pairing, or offline builds, or a machine w/o sudo).  I pretty much re-wrote both of them, and did some fairly good testing.  They should be much easier to use now!  See the commit messages for details on the changes...

Updated pairing and antlr install scripts

---

src/logger.c

Looks like abort is defined in stdlib.h, but was indirectly pulled in on all my test systems, so I missed that include :)  Here's a patch.

Fixed warnings in logger.c

---

src/httpd_dacp.c
src/player.c

This should restore the old behavior (before the persistent queue change) in "dacp_reply_cue_play" if "command" parameter is not "playnow" (plus some additional log message in player.c).

Fix for dacp-cue-play request

---

src/db.c

The mpd command "delete" with a given range of queue positions failed (due to an invalid query filter and a wrong assumption on my end, see commit message).

Fix mpd delete (by pos)

---

src/spotify.c
src/spotify_webapi.c
src/spotify_webapi.h

Reading the user country from the spotify web api requires an additional scope (user-read-private). This means you need to reauthorize forked-daapd through the web interface to make it work. If forked-daapd cannot read the user country the behavior is the same as before.
I am not sure if this is the best approach. This requests the user information on each token-refresh. Another way to do it would be to request the information once and store it in the db. 
The diff is a bit larger than necessary due to moving some functions around.

[spotify] Retrieve playlist tracks based on user country

---

src/db.c
src/db.h
src/httpd_dacp.c
src/library.c
src/mpd.c
src/player.c

Hi @ejurgensen, this should address the issue with remote when clearing the up-next queue. It should only affect dacp clients (at all the other places queue-clear is called, playback has already stopped).

Keep the now playing item in the queue when calling playqueueedit_clear

---

src/db.c
src/db_upgrade.c
src/library/filescanner.h
src/library/filescanner_ffmpeg.c
src/misc.c
src/outputs/cast.c
src/spotify.c

The first four commits are cleanups (there should be no functional changes) i found while working on support for non-library-items. The last three commits fix some (minor) problems i encountered:
- "artist_override" for spotify playlist tracks did not work
- In rare cases playing a spotify track did not succeed due to the track still being loaded (especially shortly after a restart of forked-daapd). Instead of registering all spotify tracks read from the web api with libspotify, a track is now only registered/loaded during playback setup.

Cleanup and minor fixes for spotify integration

---

src/spotify.c

After (re) authenticating forked-daapd to access the spotify web api it makes sense to first purge existing spotify songs from the db before scanning them through the web api.

[spotify] Purge spotify songs from db before scanning after oauth

---

src/spotify.c
src/spotify_webapi.c

I noticed that the spotify playlist folder always gets added to the db, if forked-daapd is compiled with --enable-spotify. This happens even if the user did not authenticate forked-daapd to access a spotify account. The first commit moves the creation of the base playlist after successful authentication (either through the web api or with libspotify).
The second commit removes the log messages for a token request (the contents was already written to the log in a previous debug message).

Avoid adding spotify playlist folder 

---

src/db.c
src/db.h
src/library.c
src/library.h
src/library/filescanner.c
src/library/filescanner.h
src/library/filescanner_playlist.c
src/mpd.c
src/spotify.c

There are two parts in this pr. The first refactors the scanning of metadata. In the current code the library knows how to scan metadata and has an ugly dependency to the filescanner. With these changes the library source is the only one who knows how to read metadata for a supported path. The library only does the general source agnostic metadata fixup.
The second part introduces a new scan_media function to the library, that takes a path that does not need to be in the library. For now only http-urls are supported. Together with the changes in mpd.c, forked-daapd is now able to add arbitrary http-streams to the queue.
For example the following mpc command now works:
```
mpc add http://path-to-radiostream
```

Refactor scanning of metadata and support for adding internet radio streams

---

src/spotify.c

This fixes empty spotify playlists, if scan happens with the web api. The problem was, that if the spotify file did not change, it was skipping the insert into the playlistitems table.

[spotify] Fix empty spotify playlists

---

src/db.c
src/db.h
src/httpd_dacp.c
src/mpd.c

It is more of a workaround than a proper fix for #366. But it keeps the changes at a minimum. If shuffle is on, playback starts now at the selected track.
The command sequence in dacp_reply_playqueueedit_add is:
- stop playback
- find selected song id
- add songs to queue (and shuffle the queue)
- move selected song to the beginning of the shuffle queue
- start playback with the selected song

[dacp] Start playback from selected song in shuffle mode

---

README.md
src/library/filescanner.c
src/mpd.c
src/remote_pairing.c
src/remote_pairing.h

These changes allow to pair a remote (e. g. Apple Remote or Retune) by using the mpd sendmessage command. 
forked-daapd makes use of the 'sendmessage' command from the mpd protocol (https://www.musicpd.org/doc/protocol/client_to_client.html). A mpd client can send a message to the channel 'pairing' with a message consisting of devicename and pin separated by a colon ':'.
With mpc this wil look like:
```
mpc sendmessage pairing "My device name:1234"
``` 
@ejurgensen Do you know why multiple pairing requests are supported by forked-daapd (linked list of devices that announced a pairing request through mdns)? I think it is highly unlikely that a user wants to pair two devices at once. It should be enough to remember the last paring request and discard a previous one. That would eliminate the …

Support remote pairing over mpd protocol

---

src/mpd.c

This pr allows controlling output volume through the mpd sendmessage command as suggested by @LordMyschkin. The channel is `outputvolume` and the message consists of the output id and the volume separated by a colon.
Using mpc setting the volume to 50% for speaker with id = 0 looks like
```
mpc sendmessage outputvolume "0:50"
```
Note that the output id is *not* the id shown by `mpc outputs` because mpc adds one to the id reported by the server. 
I am not sure if this is really helpful. Maybe @snizzleorg and @LordMyschkin can say if it is something they can make use of.
This pr is based on #373

Set speaker/output volume with mpd sendmessage command

---

src/misc.c
src/misc.h
src/mpd.c
src/spotify_webapi.c

It would be nice, if forked-daapd has a simple way to create a new string without the need to check for out of memory situations. I know there are the different CHECK macros, but none of them really fits and in my opinion a function improves the code readability.

Wrapper function for asprintf

---

configure.ac
src/dmap_common.h

gperf-3.1 generates lookup functions that take a size_t length
parameter instead of unsigned int.
Fix is more or less the same as used in systemd https://github.com/elogind/elogind/commit/947a6c107a40f43b64adb3736a495e47caad7414

fix the compilation problem because of gperf changes in 3.1

---

.travis.yml

I noticed that travis builds do not fail if there are compile errors. The "--status-bugs" option only returns an error code if there are scan build issues and apparently success if compilation failed.
Running make as a separate step in the travis build makes sure that it fails if there are compile errors.
Build with a compile error without this pr:
https://travis-ci.org/chme/forked-daapd/builds/246714070
Build with a compile error with this pr:
https://travis-ci.org/chme/forked-daapd/builds/246716807

[travis] Run separate make command in travis build

---

forked-daapd.conf.in
src/conffile.c
src/db.c
src/db.h
src/library.c
src/library.h
src/library/filescanner.c
src/library/filescanner.h
src/library/filescanner_playlist.c
src/listener.h
src/mpd.c

The mpd protocol offers commands to create/edit/delete local m3u-playlists. This pr adds some support for it in forked-daapd.
The commands supported are:
Not supported commands are:
The playlists are identified by their virtual path. The virtual path can be quite long, therefor i added a config option to define a default playlist folder. Playlists in this folder can be addressed simply by their name. 
I still need to do some more tests, but from my side this is good for a first review. The changes should not break existing functionality. This pr also includes the changes from #381.

[mpd] Initial support for stored playlists

---

src/httpd.c
src/library/filescanner.c
src/misc.c
src/misc.h

Looks like `realpath` with NULL as second parameter does exactly the same as `m_realpath` (since POSIX.1-2008, see http://man7.org/linux/man-pages/man3/realpath.3.html).

[misc] Replace m_realpath with realpath from stdlib.h

---

htdocs/admin.html

This slipped through ... should address the cluttered title bar you mentioned.

[htdocs] Fix size of stats heading on mobile devices

---

src/httpd.c
src/httpd_jsonapi.c

... when compiling without --enable-spotify

[httpd/jsonapi] Fix unused variables

---

README.md

Addition to set out the steps for accessing a shared library outside the local network. I haven't included anything on port forwarding with ssh, as that is fairly general, but the DNS step was non-obvious so I have specified the exact command.

[docs] Add instructions for remote access

---

htdocs/admin.html
htdocs/css/forked-daapd.css
htdocs/js/forked-daapd.js
src/httpd_jsonapi.c
src/lastfm.c
src/lastfm.h
src/listener.h
src/main.c
src/websocket.c

This integrates the last.fm login/logout into the web interface.
It also changes the layout of the web interface (see screenshots). I think the new layout will better scale if additional options/configurations) make it into the web interface.
last.fm login:
last.fm logout:

Integrate last.fm into web interface

---

README_PULSE.md
forked-daapd.conf.in
src/conffile.c
src/outputs/pulse.c

This is needed to access a pulseaudio server via TCP.
If server is not specified in configuration, the behaviour is unchanged.

allow specification of pulseaudio server

---

forked-daapd.conf.in
src/conffile.c
src/library/filescanner.c

I have a lot of ´symlinks,which leads to duplicate entries and a lot of spam in the log.
By ignoring symlinks, real errors become visible again.
The default is to follow symlinks.

[scan] configuration option to follow symlinks

---

src/mpd.c

When there is an album directory containing quotes, e.g.:
Charlie "The Bird" Parker: Portrait 01 ~ Groovin' High
If quoted MPD arguments are not unescaped, the virtual path is not found:
Directory info not found for virtual-path '/file:/srv/music/Charlie Parker/Charlie \"The Bird\" Parker: Portrait 01 ~ Groovin' High'
This pull request fixes this.

[mpd] Quoted argument unescaping fixed

---

src/library/filescanner.c

While testing the `database`/`update` events, I found that after an `update` command, the automatic detection of filesystem changes did not work anymore.
This change fixed it.

[scan] After rescan, fullrescan inotify must be enabled

---

src/db.c

When a music tree contains directories with trailing spaces, they are not found in the database during a rescan, because sqlite removes the trailing space in the database. These non-changes are reported as changes  triggering library reloads and cache updates.
I think at least a hint in the log file would be most helpful.
BTW: The correct solution would be to store directories with a trailing slash, but it does not help with files having trailing spaces.

[db] Report directory names that end in spaces

---

src/cache.c
src/db.c
src/db.h
src/httpd_dacp.c
src/httpd_streaming.c
src/inputs/pipe.c
src/library.c
src/library.h
src/listener.h
src/mpd.c
src/websocket.c

I rebased #436, squashed some commits and did some small cleanups (mainly some code documentation, naming).
The  changes are (for details see the discussion in #436):
- fix the idle command handling: do not lose events if a mpd client is not in idle mode
- store last update time of the library in the admin db table and report the update time in the mpd stats command
- fix for sending database event on init-/rescan even if nothing changes
- change listener implementation to support notifying of multiple events in one call (required to properly send the DATABASE/UPDATE events to mpd clients)
- notify mpd clients of DATABASE and UPDATE events 
- fix noidle command: report change events in noidle response (if any exist)
@wolfmanx Thank you for working on this! I hope it is ok, that i picked …

[mpd] Notify MPD clients of library changes and fix idle command

---

src/library/filescanner.c
src/library/filescanner_playlist.c

When adding a http stream URL to the playlist with an `add` command, the virtual path is just duplicated from the URL.
When the playlist is then retrieved via `playlistinfo`, the leading character `h` is cut off, which causes problems in e.g. cantata.
This fixes it, but I don't know what the implications are.

[scan] Consistent HTTP virtual paths

---

src/db.c

When playing HTTP streams, the metadata changes are not detected by cantata.
Comparison of the conversations between the client, MPD and forked-daapd shows that MPD triggers a `changed: playlist` event when the metadata changes.
This PR makes the metadata update work in cantata and does not seem to have an adverse effect on DAAP clients (Retune, Remote).

[db] Queue notification when metadata changes

---

src/mpd.c

@chme Several functions use a different algorithm to construct a playlist name, which leads to errors.

[mpd] Consistent playlist name setup

---

src/httpd.c
src/httpd.h
src/main.c

This adds a command line parameter for setting the web root directory:
```
./forked-daapd -w <path to webroot directory>
```
It makes development of the web interface a bit more convenient, as it is now possible to point the web root directory directly to the source folder. I think this is in line with the parameters for the config file or the pid file.

[main/httpd] Configurable web root directory over cli parameter

---

src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/mpd.c
src/player.c

Fixes #446 by making the queue item ids unique (not reusable after e. g. a queue clear) and implements the mpd commands 'plchanges' and 'plchangesposid' correctly (only return changed items and only in the given range).
This pr contains a db update from version 19.05 to 19.06 (i hope a minor version increase is correct):
- queue table: define id column as AUTOINCREMENT (requires drop+create)
- queue table: add column queue_version
- files table: update http-stream virtual paths (constructing the virtual path for http-streams changed in pr #449, this migrates existing databases to be consistent to the newly created paths)
As mentioned in #446 adding a queue item could result in the SQLITE_FULL error, if the autoincrement id reached its max value 9223372036854775807. I think that it is …

Unique queue item ids and proper implementation of mpd commands 'plchanges' and 'plchangesposid'

---

src/httpd_jsonapi.c
src/websocket.c

Like pr #457 this pr adds new endpoints to the JSON/websocket api to query and control playback.
It is part of my work towards a simple web interface to control forked-daapd (https://github.com/chme/forked-daapd/tree/web_remote).

Endpoints to query/control playback through JSON/websocket api

---

src/db.c

This fixes a regression introduced in 912635e737319e2ec5d24f2922b3f31b38c8a88c that results in an error when trying to add a url to the current queue that is not in the library (e. g. `mpc add http://stream`)

[db] Fix adding urls to the queue that are not in the library

---

src/mpd.c

The noidle command did not prevent idle events to be sent to the client directly when they occured. This resulted e. g. in M.A.L.P. in errors trying to play an album from the library.

[mpd] Fix 'noidle' command handling

---

src/logger.c

This change saved 4 seconds from the startup scan in my not representative tests (raspberry pi 2 with 9430 songs). Normally the scan takes ~51 seconds and with this change it went down to ~47 seconds (no new/changed files).
It's not much ...

[logger] Return early if severity or domain do not match

---

src/db.c
src/mpd.c

Some MPD protocol support improvements:
- Report current and next song in 'status' and 'currentsong' commands (if the config of clear_queue_on_stop_disable = true, then clients are now able to display the next song if player is stopped)
- Implementation for commands 'playlistfind' and 'playlistsearch'
- Support for position parameter in command 'addid' (e. g. M.A.L.P. makes use of this to add a song as the next item in the queue)

MPD protocol support improvements

---

src/mpd.c

cantata uses the response from command `urlhandlers` to check, whether a stream URL is allowed to be added. This minimal `urlhandlers` implementation allows to add HTTP streams.

[mpd] minimal urlhandlers command

---

src/db.c
src/spotify.c

With these changes scanning saved spotify albums/playlists require webapi access authorization. This simplifies the handling in spotify.c and reduces the usage of libspotify. 
I need to do some more testing, but it is good for a first review.

[spotify] Remove scanning saved playlist with libspotify

---

forked-daapd.conf.in
src/cache.c
src/conffile.c
src/db.c

This adds a config option to allow setting the sqlite3 pragma "mmap_size" to enable memory mapped io in sqlite3 (https://www.sqlite.org/mmap.html).
Enabling it saves some data copies and therefor has a small performance gain. I am running forked-daapd with this enabled for month and did not encounter any issues. On my setup (raspberry pi 2), i have the feeling, it gives a small performance gain (especially when the system is under load, e. g. playing and loading artwork, ...), but i have to admit, that there was no measurable gain during startup/rescan.

Add option to enable memory-mapped I/O for sqlite3

---

src/inputs/pipe.c

@ejurgensen totally untested, but this should fix the automatic listening for pipes (https://github.com/ejurgensen/forked-daapd/commit/1cdb9f450d385618dbfc3ed8b04d2bea9900dbbb#commitcomment-26516503).
The cache should be fine. If the database did not change, there is no need to rebuild it. If the cache file was deleted, there is also no need to rebuild the cache as there are no cached daap-replies (the cache tables are created during cache init).

[pipe] Do not rely on the DATABASE event to be triggered during startup

---

src/db.c

Fixes missing queue updates in MPDroid after moving an item in the queue. MPDroid moves items with the 'moveid' command and retrieves the playlist changes with the 'plchanges' command, due to the missing queue_version update the last command did not return any changes and the queue in MPDroid did not get updated.

Fix for missing queue updates in MPDroid

---

src/mpd.c

Reduce code duplication by adding a generic check for the minimum arguments required for the mpd protocol commands (like @wolfmanx did for the sticker command).  Also reformat the command definition array for better readability.

[mpd] Refactoring of minimum argument check

---

src/player.c

Adds checks in playback_stop and playback_pause for the correct player state (playing, paused, stopped) and handle them gracefully in case player does not have the correct state for the action. 
I think dacp/daap clients only allow the stop/pause/next/prev actions to be triggered if the player state is correct. But this is not the case with mpd clients. This does currently not lead to real issues, but shows unnecessary error logs.

[player] Check player state in stop and pause commands

---

configure.ac
src/db.c
src/logger.c
src/logger.h

This pr makes it a bit more convenient to analyse db queries used in forked-daapd.
It adds a configure switch (`--enable-dbprofile`) to activate the already present profiling support in forked-daapd. And additional updates the profiling support to avoid using deprecated sqlite3 functions.
To minimize performance impact due to active profiling, the logger now exposes the log severity and the profiling function returns early if no log entries would be written.
Here is an example log output:
```
[2018-01-13 11:18:20] [  LOG]   dbperf: SQL PROFILE query: SELECT f.genre, f.genre FROM files f WHERE f.disabled = 0 AND (((f.media_kind = 1 OR 1 = 0) AND (f.genre <> '' AND f.genre IS NOT NULL))) AND (f.data_kind <> 1) AND f.genre != '' GROUP BY f.genre ORDER BY f.genre ASC ;
[2018-01-13 11:18:20] [ …
```

[db_profile] Use sqlite3_trace_v2 instead of deprecated sqlite3_profile

---

src/db.c
src/library.c

The "ANALYZE" statement takes around 2 seconds on my raspberry pi. It is called twice during startup (first at db_init, second after initscan).
According to the sqlite3 documentation it is recommended to use the "PRAGMA optimize" statement instead (https://www.sqlite.org/lang_analyze.html), which will call "ANALYZE" if it is likely the new data is helpful.
It does not make a big difference during startup ... but i thought i post it here nevertheless.

[db/library] Use "PRAGMA optimize" instead of "ANALYZE"

---

forked-daapd.conf.in

"Syncronization" should be "Synchronization".

Fixed typo in comment

---

README_JSON_API.md
src/db.c
src/db.h
src/httpd.c
src/httpd.h
src/httpd_jsonapi.c
src/misc.h

@ejurgensen i know you are not so thrilled about expanding the JSON api to an extent that allows building full fledged applications based on it. But the current possibilities - daap/dacp and mpd - have all drawbacks, so that i believe, a client protocol that is in our control would really be beneficial to forked-daapd.
It would allow building clients that make fully use of the features in forked-daapd, e. g.:
* Control volume for individual outputs (something mpd clients cannot do)
* Display separate lists for audiobooks, podcasts, music, ... (something mpd clients cannot do)
* List files in a directory structure (something the dacp/daap clients cannot do)
* Save and modify playlists in the library (something dacp/daap clients cannot do)
* ...
A new protocol (with new client applications) …

New endpoints for the JSON api (library, queue)

---

forked-daapd.spec.in

- Added new web interface files.
- Updated with/without options to reflect configure defaults.
- Updated build dependencies.
- systemd no longer a hard requirement.
- Other cleanups to match Redhat standards.

[config] Update rpm spec to version 26.0

---

src/db.c
src/db.h
src/httpd_dacp.c
src/library.c
src/library.h
src/library/filescanner.c
src/library/filescanner.h
src/library/filescanner_playlist.c
src/mpd.c

This refactors how paths, that are not in the library, are added to the queue (currently only supports internet radio urls). Before, the client protocol implementation (mpd.c) had to first scan the url into a media_file_info and than add this media_file_info to the queue. This is simplified by this pr by adding a "queue_add" function to the library source implementations. In mpd.c it is now enough to pass the url to queue_add and queue_add takes care of creating and adding the queue items.
This is an intermediate step towards support for adding spotify uris to the queue that are not in a saved playlist or album. It opens the possibility that a given path/uri translates to more than one queue item (e. g. a spotify album uri).
It also addresses the issue that @wolfmanx  reported and worked …

Refactor adding non library items the queue

---

README_JSON_API.md
src/db.c
src/db.h
src/httpd_jsonapi.c
src/mpd.c

Some additions to the JSON API:
- new count endpoint
- additional metadata in track object (time added/played, date released, resume point)
- a fix for the cache-control headers (check if a resource was modified was done on the startup time but should be done on the db update time)
The one change that also affects mpd is adding artist and album count to the filecount_info struct. This allows to get rid of the count artist and album functions.

Add count endpoint to JSON API and fix cache-control headers for library endpoints

---

src/httpd_jsonapi.c
src/httpd_oauth.c
src/spotify.c
src/spotify.h
src/spotify_webapi.c
src/spotify_webapi.h

This pr splits the scanning of saved spotify playlists and albums (using the spotify web api) from playing a spotify track (using libspotify).
I have some more changes in preparation, that will add further code to spotify_webapi.c (https://github.com/chme/forked-daapd/tree/spotify_rework) and thought a refactoring is necessary. It is currently not so easy to understand how the spotify integration in forked-daapd works. The clean separation of the playback logic (spotify.c) from scanning saved tracks into the library (spotify_webapi.c) should make this easier.  
This pr needs a great deal of further testing, but the change is huge, which is why i wanted to post it early.

Refactor spotify integration

---

src/artwork.c
src/artwork_legacy.c
src/httpd_jsonapi.c
src/inputs/spotify.c
src/spotify.c
src/spotify.h
src/spotify_webapi.c
src/spotify_webapi.h

This is based on #507, but i thought i put it out to give some incentive to merge/proceed on #507 :-)
The goal is to allow forked-daapd to play any spotify track and not only those in a saved playist/album. With these changes this can be done by adding a spotify track/album/playlist uri to the queue, either through the web api (`/api/queue/items/add`) or the mpd-protocol (e. g. `mpc add`). 
Another change included in this pr is exposing the spotify web api access token through the JSON API. Not sure what you think of this, but it was the easiest/most convenient way to integrate in the web interface.

Allow playing arbitrary spotify tracks

---

src/httpd_jsonapi.c
src/player.c

I noticed that setting volume for an individual speaker from mpd or json does not always result in a correct update of the master volume. The problem occurs if the volume of the speaker is changed that defines the master volume and after the change another speaker would define the new master volume.
For DACP clients this is working because in that case they send two requests to forked-daapd. The first one for the speaker the volume should change and the second for the new "master" speaker.
To avoid having to send two requests in mpd.c and httpd_jsonapi.c, i added an option to force a master volume update in volume_setabs_speaker and volume_setrel_speaker.

Fix setting speaker volume from mpd/json

---

src/websocket.c

See title (also "fixes" #532 by logging libwebsockets logs with severity NOTICE as INFO into the forked-daapd log. By default libwebsockets logs all messages to stderr)

[websocket] Properly log libwebsockets log messages

---

README_JSON_API.md
src/httpd_jsonapi.c

Add endpoints to:
* list all `genres` known to server
* search by `genres`, returning all albums matching a `genre`
modeled heavily on existing `album` code.
Functionality would be coupled with update to UI that would allow users to queue music by a given genre, such as classical.  Currently, users need to locate and queue individual songs/artists/albums.
~~Missing updates to web ui for which an issue https://github.com/ejurgensen/forked-daapd/issues/558 is logged~~  Web ui (generated/drop-in `htdocs` files) updates on a fork:
~~https://github.com/whatdoineed2do/forked-daapd-web/files/2258629/dist-0cd890b3128c50510c776d455adb0c61a9b3b376.tar.gz~~
~~[dist-search-genre-98ce8de37dfda03a766e5745e5e1219be764545b.tar.gz](https://github.com/ejurgensen/forked-daapd/files/2288253/dist-search-genre- …

genre search functionality

---

src/player.c

Incrementing playcount and trying to scrobble non persistent queue items is not necessary and produces error log messages.
Non persistent items are also not correctly shown in the queue history (only shown in dacp clients). It would be nice to display them correctly, but this is a bigger change (for imo little gain). The second commit just avoids adding them to the history.

Fix error logs for non persistent queue items

---

src/httpd_dacp.c

Since the change to store the queue in the db, the span parameter from dacp clients was not taken into account (and the client always got the whole queue instead of the requested number of items). This should fix #556.

[dacp] Only return requested number of queue item (fixes #556)

---

forked-daapd.conf.in
src/conffile.c
src/db.c

If i have done it right, this will implement the logic for calculating ratings like it is done in the beets mpdstats plugin (https://beets.readthedocs.io/en/latest/plugins/mpdstats.html).
For lazy people like me, that do not manually set ratings, this adds an easy way to get ratings based on how often a song is played and skipped. 
Ref: #249

Add automatic calculation of ratings based on played/skipped

---

src/db.c
src/db.h
src/httpd_dacp.c
src/httpd_jsonapi.c
src/mpd.c
src/player.c

As a prerequisite for #581, this pr adds the functions to add new queue items into the middle of the queue.
It also adds to new output parameters to the queue add function, count and item-id. This is a preparation to add these information to the JSON API. This information would allow clients to append to the queue and start playback at the first inserted item. The count value is useful to display the number of items added to the queue, e. g. after adding an album.

[db] Add support to add items to the queue at a specified position

---

forked-daapd.conf.in
src/conffile.c
src/outputs/alsa.c

The unconfigurable resync period of 10 seconds was not frequent
enough to keep my own ALSA device in sync with the AirPlay stream.
Now the period is configurable.  The default is still at 10
seconds, to prevent any change in behavior unless opted in by
the user.
Currently the adjustment causes a tiny "click" distortion in the
ALSA output, so it is better to make the check as infrequent as
possible, while still being frequent enough to stay in sync
over lengthy sessions of playback.
Added source_sample_rate, target_sample_rate to alsa_session.
This is a first step toward rendering ALSA at a different
sampling rate than the AirPlay stream, so that (a) we will
be able to dynamically adjust the ALSA sampling rate for an
improved sync algorithm, and (b) later, a more generalized
resampling …

Made resync period configurable 1..20 seconds, with default=10.

---

src/library/filescanner_playlist.c

Fixes https://github.com/ejurgensen/forked-daapd/issues/608
Recognise `https` streams in `m3u` playlist files - the backend can play `https` streams fine with no further changes once patch applied

[filescanner] parse https streams for m3u

---

README_JSON_API.md
src/db.c
src/db.h
src/httpd_jsonapi.c
src/library.c
src/library.h
src/library/filescanner.c
src/mpd.c
src/spotify_webapi.c

Alternative to #581
@whatdoineed2do This is what i had in mind on how to support the "position" parameter in the `queue/items/add` endpoint. A different endpoint for adding items after the current playing one is not necessary. Instead the web interface knows at which position in the queue the now playing item is and calls `queue/items/add` with this position + 1.
This pr also adds the "add next" functionality to the Spotify views in the web interface (this is missing in #581). @ejurgensen Adding support for this required some changes to the db/queue handling for non library items.

[jsonapi] Add support for a position parameter in the queue/items/add endpoint

---

src/db.c
src/db.h
src/library.c
src/library.h
src/library/filescanner.c
src/player.c
src/spotify_webapi.c

Two fixes for errors i noticed in the player web interface (might also affect mpd clients):
- Turning shuffle mode off did not update the queue in the player web interface
- Adding non library items to the queue with shuffle mode on, does not reshuffle the queue

Fixes for shuffle mode in player web interface

---

README_JSON_API.md

Fix for #618
Probably easier to read the README in my branch:
- Documentation for `/api/update`
https://github.com/chme/forked-daapd/blob/jsonapi/README_JSON_API.md#trigger-rescan
- Also added documentation for `/api/library`
https://github.com/chme/forked-daapd/blob/jsonapi/README_JSON_API.md#library-information

[README] Document JSON API endpoints /api/update and /api/library

---

src/spotify_webapi.c

Saved albums and playlist items have a "added at" attribut. With this pr this "added_at" value is used as the tracks "time added" and "time modified" value (instead of the current time).
It's not perfect, but using the current time, leads to unexpected results, in smart playlists/queries where "time_added" and "time_modified" are used.

[spotify] Set track fields "time added" and "time modified" 

---

README_JSON_API.md
src/artwork.h
src/db.c
src/http.c
src/httpd_jsonapi.c
src/mpd.c
src/outputs/raop.c
src/spotify_webapi.c

This pr fixes wrong artwork urls for items in the queue, that are not in the local library or are streams that support artwork as metadata. The later is an assumption based on the code and not (yet) tested. @ejurgensen could you point me to a radio stream that supports artwork? The ones in my library do not seem to provide artwork metadata.
Another change included in this pr is, that spotify queue items, that are not part of the library, now provide an artwork url (taken from the spotify web api).

[jsonapi] Artwork url for non library items and streams

---

src/player.c

Currently forked-daapd returns an error trying to pause playback of a radio stream. This pr tries to handle this more graceful by stopping reading from the stream (closing it) on pause and reopening the stream if playback is resumed.
This is rather complex territory and i might have made some false assumptions. But in my short test so far it seems to work fine.
The first commit is not entirely related, but i think this should fix errors when pausing in the last two seconds of a song.

Improve pausing radio streams

---

README_JSON_API.md
src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/httpd_jsonapi.c

Feature request: https://github.com/ejurgensen/forked-daapd/issues/614
Add `composer`to `queue` table and displaying on `Now Playing` page if `composer` is exposed by `httpd_jsonapi`

Display composer on Now Playing page

---

src/httpd_jsonapi.c

`jsonapi_reply_queue_tracks_add` is called to queue track(s) - the new web interface reports the number of tracks Q but this is currently incorrect as `count` is reset to `0` at the top of the `do-while()`.
Simple fix to correct.

[jsonapi] correct count of tracks added returned

---

.travis.yml
src/db.c
src/db_upgrade.c
src/evrtsp/rtsp.c
src/httpd_daap.c
src/inputs/pipe.c
src/library/filescanner_ffmpeg.c
src/outputs/alsa.c
src/outputs/raop.c
src/player.c

The xenial build environment is available in travis-ci (https://blog.travis-ci.com/2018-11-08-xenial-release).
Unfortunately the libwebsocket-dev version in xenial is still to old to build with websockets enabled. 
But the new scanbuild version finds some new issues. I fixed 3 of them and i think the others might be false positives. @ejurgensen it would be good if you too can take a look at them.

[travis-ci] Update build environment to Ubuntu 16.04

---

src/db_init.c

Fix missing creation of triggers for persistent ids in db init. Leads to all persistent ids in the files table being 0.

[db] Fix missing creation of triggers for persistent ids in db init

---

README_JSON_API.md
src/http.c
src/httpd_jsonapi.c
src/websocket.c

- Allow adding new items to the queue by query language, add new optional parameters to start playback after adding new items (closes #641)
- Fix ordering of tracks in `library/files` endpoint
- Fix segfault if an empty `uris` parameter is passed to `queue/items/add` endpoint
- Include configured library directories in `config` endpoint
- Add missing "database" notification to `websocket.c`

[jsonapi] Allow adding items by query language to the queue (plus some small fixes)

---

README_JSON_API.md
src/httpd_dacp.c
src/httpd_jsonapi.c
src/mpd.c
src/player.c
src/player.h

As proposed in #658 this pr implements a toggle endpoint to toggle between play/pause.
Additionally i added support for increasing/decreasing volume instead of always setting the absolute volume level in `api/player/volume`.
@ejurgensen I wanted to get rid of the workaround to get a single speaker_info and therefor added a new command in player.c.
Closes #658

New JSON API endpoint player/toggle and support for volume steps in endpoint player/volume

---

src/misc.h
src/mpd.c

Fixes a segfault i encountered with the `listplaylistinfo` command in combination with setting a default playlist directory (forked-daapd.conf) due to a mistake in the creation of the virtual path (wrong format string used for asprintf).
@ejurgensen Could you take a quick look at the change in `misc.h`? To avoid this mistake in the future i added a compiler function attribute that will spit out compiler warnings in case format string and/or format parameters do not match.

[mpd] Fix segfault

---

src/player.c

Fixes #674. The segfault was introduced in #668 (i was sure, that i did test the last version i submitted. But that was obviously not the case ...)

[player] Fix segfault when getting single speaker/output by id

---

README_JSON_API.md

The API document README_JSON_API.md lists /api/player/prev, but /api/player/previous is the endpoint that works.

Fix API documentation for player/previous endpoint

---

README_JSON_API.md
src/db.c
src/db.h
src/httpd_jsonapi.c
src/library.c

I started using forked-daapd to listen to podcasts and therefor am looking into improving the podcast section in the web interface. One thing missing in the JSON API is, that it is not possible to mark a podcast episode as already played. 
The new endpoints are:
- GET api/library/tracks/{id}: get metadata for a single track
- PUT api/library/tracks/{id}: update play count and/or rating for a single track

JSON API endpoints to get a track and modify rating, play count

---

src/artwork.c
src/http.c
src/http.h
src/spotify_webapi.c
src/spotify_webapi.h

It seems that Spotify has stopped serving artwork images over libspotify (at least on my machines i always get unknown image format and data size = 0 as response).
This pr works around this issue by introducing a new artwork source for Spotify tracks using the Spotify web api.
This new artwork source is only used, if loading artwork through libspotify failed.
(Not sure if we should remove the artwork source for libspotify ...)

[spotify/artwork] Add spotify webapi as an additional artwork source

---

src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/httpd_jsonapi.c
web-src/src/components/ModalDialogQueueItem.vue

The web ui's `queue item` modal is inconsistent with other modal's (such as Artist modal) which has clickable links to album and atrist
This PR makes adds the same clickable links for the `queue item` modal.
Requires the `queue` table to be extended to carry `songartistid` - it was already carrying the `songalbumid`; both these are exposed by the `jsonapi`'s `/api/queue` endpoint as new elements for each `queue item`

[db,web-src] support links to album,artist from queue item modal like others modals

---

src/SMARTPL.g
web-src/src/components/ListItemTrack.vue
web-src/src/components/ModalDialogTrack.vue
web-src/src/mystyles.css
web-src/src/pages/PageBrowse.vue
web-src/src/pages/PageBrowseRecentlyAdded.vue
web-src/src/pages/PageBrowseRecentlyPlayed.vue
web-src/src/pages/PagePodcast.vue
web-src/src/pages/PagePodcasts.vue
web-src/src/webapi/index.js

Improve podcasts views in player web interface
- Add a "new episodes" section in the podcasts view
- Add new, played and progress visual indication
- Add button in details view to mark as played/new
Screenshots:
**Note**: This PR does not include the generated htdocs files! I will add new generated htdocs files in a separate pr (want to include some other changes before bumping the web interface).

Improve podcasts views in player web interface

---

README_JSON_API.md
src/httpd_jsonapi.c
web-src/src/components/ModalDialogQueueItem.vue

Small fixes/adjustments to the queue item details dialog:
- Only link to album/artist if there is a valid id
- Rename `albumartist_id` to `album_artist_id` (keep naming between queue item and track in sync)

Small fixes/adjustments to the queue item model

---

src/httpd_streaming.c
web-src/src/audio.js
web-src/src/components/ModalDialogQueueItem.vue
web-src/src/components/ModalDialogTrack.vue
web-src/src/components/NavBarItemOutput.vue
web-src/src/components/NavbarTop.vue
web-src/src/pages/PageAlbum.vue
web-src/src/pages/PageArtist.vue
web-src/src/pages/PageAudiobook.vue
web-src/src/pages/PageFiles.vue
web-src/src/pages/PageGenre.vue
web-src/src/pages/PageGenreTracks.vue
web-src/src/pages/PagePlaylist.vue
web-src/src/pages/PagePodcast.vue
web-src/vue.config.js

Closes #621
- adds a "HTTP stream" item to the list of outputs in the menu (see screenshot)
- volume control for the http stream is not tied to the master volume
- removes the timeout handling in `httpd_streaming.c`
This need some more testing (especially with different browsers), but initial tests are promising.
@ejurgensen was there a specific reason to add a timeout to the streaming request? This timeout resulted in the stream being interrupted every 60 seconds. I checked with vlc and there this timeout also kicks in. vlc handles this gracefully by directly reconnecting, but this is a bit inconvenient for streaming in the browser ... is it not enough to stop sending data when the connection closes? (I checked another radio stream and there no timeout is used.)
----
Screenshot

Add option to stream audio from web interface

---

src/spotify_webapi.c

Spotify introduced new endpoints for playlists: https://developer.spotify.com/community/news/2019/01/15/update-changes-to-playlist-uris/
As i understand it, the playlist uris might also change at one point, this would lead to problems adding a Spotify playlist that is not in the library to the queue (over the player web interface).
The first commit should address this by only parsing the playlist id and not the owner from the playlist uri and switching over to the new playlist endpoints.
The second commit adds the functionality to add a Spotify artist uri to the queue (currently this leads to a segfault, if triggered from the player web interface).

Switch to new Spotify web api playlist uris and support adding artist tracks to queue

---

forked-daapd.service.in

This simple PR adds `MemoryMax` limit to the control group that the server runs, enforcing an upper limit of memory.
This helps to prevent **malformed user generated** `SMARTPL` queries (initiated by `curl`)  (see https://github.com/ejurgensen/forked-daapd/issues/570) from putting the server into a infinite loop and causes process to consume all ram / freeze the system until OOM killer finds it.
In the event that `forked-daapd` starts to eat memory, `cgroup` handling will kill it once it reaches the set memory threshold (which is beyond normal usage scenarios from what I've seen) - the restart logic/settings in the same service file will bring the server back.
I've had this running on my main production machine (Raspberry Pi) and development boxes for a while and works well.

[systemd] add MemoryMax to service

---

.travis.yml

This updates the travis-ci build environment from Ubuntu Xenial (16.04) to Bionic (18.04).
Instead of relying on the distributions provided by travis-ci, forked-daapd is now build in the latest Ubuntu LTS docker image.

[travis-ci] Build forked-daapd in the latest Ubuntu LTS docker image

---

src/websocket.c

[websocket] disable ipv6 in ws_init if disabled in config

---

src/inputs/file_http.c
web-src/src/components/PlayerButtonPlayPause.vue

some http streams (such as ones that mp3 files hosted on the web) are seekable whilst others (live internet radio sterams) are not.
Seekable determined if we have non-zero length

Seekable http streams

---

web-src/src/pages/PageQueue.vue

Previous PR missing the display of the modal to enter URL stream - was in my integration branch but got missed on the submitted PR

[web-src] missing modal display for URL stream (20c36cb48)

---

forked-daapd.conf.in
src/conffile.c
src/httpd_jsonapi.c
src/mpd.c
web-src/src/components/ModalDialogPlaylistSave.vue
web-src/src/pages/PageQueue.vue
web-src/src/webapi/index.js

Rebased #718 and restyled the modal dialog:
- only show "save" button if forked-daapd is allowed to modify stored playlists
- added/modified some checks

Rebased version of pr718 "save queue playlist"

---

configure.ac
src/outputs/alsa.c

Compiling on Fedora 30 doesn't appear to include /usr/include/sys by default, so the long deprecated sys/asoundlib.h isn't found on a build with ALSA.  It appears that asoundlib.h has been in alsa/asoundlib.h for well over 10 years, and other projects all just include <alsa/asoundlib.h>, so this patch does exactly that. :)

[alsa] asoundlib.h should be alsa/asoundlib.h

---

configure.ac
forked-daapd.conf.in
src/conffile.c
src/logger.c
src/logger.h
src/mpd.c

@ejurgensen I think it would be best not to break existing config files. This pr readds the old options in the 'mpd' section and displays a deprecation error in the log if they are present.
In a future version the deprecated options could then be dropped completely.

[conf] Gracefully handle the change of config options for modifying playlists

---

Makefile.am
README_ALSA.md

Readme for ALSA setup, detailing how to find cards/devices available and how the names map.  Includes discussion around the ALSA `dmix` device that may be useful (see https://github.com/ejurgensen/forked-daapd/issues/742#issuecomment-504364075)

[docs] alsa setup

---

README.md
README_JSON_API.md
htdocs/admin.html
htdocs/admin/js/forked-daapd.js
src/httpd_jsonapi.c
src/library.c
src/library.h
src/library/filescanner.c
web-src/src/pages/PageAbout.vue
web-src/src/webapi/index.js

Provide a 1/2 way house between `.init-rescan` (relies on new files or files that have changed but not picked up by server) or the `.full-scan` which drops `forked-daapd` generated/maintained data from the `files` table such as `play_count` etc.
This is useful in situations where the server supports more metadata (such as 35a585c23eab873a22aeb41232aaaabbfb24ae5e now supporting MusicBrainz tags) but we want to maintain generated meta in library that would get killed otherwise/having to manually touch/update individual files to force a normal meta-rescan

[library] support forced metadata scan of library

---

README_JSON_API.md
src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/httpd_jsonapi.c
src/library/filescanner.c
src/library/filescanner_ffmpeg.c
web-src/src/components/ModalDialogQueueItem.vue
web-src/src/components/ModalDialogTrack.vue

Add media quality info (type/bitrate/samplerate) to the `queue` table and support in jsonapi to extract for queue modal dialogue as per @chme's concerns (https://github.com/ejurgensen/forked-daapd/pull/721#issuecomment-497204271)

db queue to incl media quality info

---

src/httpd_streaming.c

Closes https://github.com/ejurgensen/forked-daapd/issues/730
Support `Icy-MetaData` client requests on http streaming, sending song "`title` - `artist`" in the _metadata_  (in `StreamingTitle='....';` string) embedded at periodic periods (8192 fix byte intervals) in the MP3 audio stream.
Also fixes shutdown race conditions in streaming cleanup.

[streaming] support sending ICY metadata (title)

---

src/httpd_streaming.c

Small fix for potential buffer overflow in 0941cf5 that will lead to core dump/garbled audio for streaming clients
Minor impact and only occurs when we have combined lengths of artist + title > 4064.

[streaming] potential icy-meta overflow fix (for artist+song title > 4064 bytes)

---

README_SMARTPL.md
src/SMARTPL2SQL.g

For dates that require context (ie today, yesterday, N days ago etc) we want the underlying SQL to respect the current time when running query;  a query that requests items for 'today' should only find matches for the time it was run.
Current implementation would generated a fixed date, `time_t` for use in comparisons, at the time the SMARTPL is inserted into db  playlist table.  This PR generates a `datetime` query for SMARTPL dates such as `today` etc and results in a SQL fragment that provides the `time_t`/unixtime at the point of execution.
ie `today` results in SQL fragment: `strftime('%s', datetime('now', 'start of day', 'localtime'))`
Closes https://github.com/ejurgensen/forked-daapd/issues/770

[smartpl] generate dynamic dates for SMARTPL queries

---

htdocs/admin.html
htdocs/admin/js/forked-daapd.js
src/httpd_jsonapi.c
src/spotify_webapi.c
src/spotify_webapi.h

Fixes #780
Requires to reauthorize forked-daapd to access the Spotify web API (with the additional scope `playlist-read-collaborative`).
The JSON API now exposes the required and granted scopes and the admin web interface displays a message, if reauthorization is necessary.

Allow reading of collaborative/shared Spotify playlists

---

src/db.c
src/db.h
src/httpd_jsonapi.c

Web interface allows retrieving a files/directory view but currently the ordering of directories and files are strictly on `virtual_path` which leads to separation uppercase and lowercase directory names:
ie the directories: `A, B, C, D, a, z` would be listing in this order whilst a user would expect them to be listed as `A, a, B, C, D, z`.  Similar comment for files which appear as a block under the directory list.
This simple PR provides case insensitive ordering on queries related to the json `/api/library/files` endpoint

[db,jsonapi] case insensitive directory/file listing

---

forked-daapd.conf.in
src/conffile.c
src/httpd.c
src/httpd_streaming.c
src/misc.h
src/outputs/alsa.c
src/outputs/cast.c
src/outputs/fifo.c
src/outputs/pulse.c
src/transcode.c

MP3 streaming is set to 44.1k/16/2 with a bit rate of 128kbps.
Streaming bandwidth on an internal (home) networks are likely to be be able to support higher bitrates than 128kbps and it is desirable to have to ability to adjust upwards the bitrate, particularly if the endpoint feeds into a DAC.
This PR adds the `library.streaming_bitrate` configuration value to allow users to select 128/192/320 bitrates.
Closes https://github.com/ejurgensen/forked-daapd/issues/503
We extend `struct media_quality` to incl `bit_rate` which is normally `0` unless we require a specific bitrate for the transcode.  Currently the transcode's `AVCodecContext::bit_rate` is defaulted to 128000 and there is no impact on setting this to 0 since it looks like `bit_rate` field is ignored during the encode side …

[streaming/xcode] configurable MP3 streaming bitrate

---

src/httpd_streaming.c

close callback, `streaming_close_cb()`, cleans up the session but not the `evhhttp_request` object alloc'd from `httpd()-> event_base_dispatch() -> ... -> event_base_loop() -> ... -> evhttp_request_new()`
This leak can be observed by:
* starting the server
* connect a streaming client to the server (`ffmpeg -i http://forked-daapd.local:3689/stream.mp3`)
* kill/disconnect the streaming client
* stop the server
```
==13137== 1,658 (216 direct, 1,442 indirect) bytes in 1 blocks are definitely lost in loss record 369 of 380
==13137==    at 0x4C3114A: calloc (vg_replace_malloc.c:762)
==13137==    by 0x8A433EC: evhttp_request_new (in /usr/lib64/libevent-2.1.so.6.0.2)
==13137==    by 0x8A4352B: ??? (in /usr/lib64/libevent-2.1.so.6.0.2)
==13137==    by 0x8A43740: ??? (in …
```

[streaming] mem leak fix on client initiated disconnect

---

src/player.c

As reported in https://github.com/ejurgensen/forked-daapd/issues/809#issuecomment-533941560 enabling/disabling an output does not reflect the master volume changes in the web interface.
This pr fixes it, by simply always sending an additional VOLUME notification, if a command for enabling / disabling an output is executed.

[player] Fix missing update of master volume in web interface

---

web-src/.browserslistrc

Reason behind this change: https://jamie.build/last-2-versions

[web-src] update .browserlistrc file

---

src/db.c
src/httpd_jsonapi.c

The artwork url in the JSON object for queue items was not correctly set, if the queue item represents a pipe input. This pr should fix this (i only tested with the dummy data from #817).
Fix #817

Show pipe artwork in player web interface

---

README_JSON_API.md
src/httpd_dacp.c
src/httpd_jsonapi.c
src/mpd.c
src/player.c
src/player.h

For podcasts and audiobooks it would be good to have the ability to skip a number of seconds forward and backward (ref #729). This draft adds this functionality to the player as a new player command (`player_playback_seek_rel(...)`). The JSON API exposes this by supporting a new parameter for the `/api/player/seek` that expects the amount of milliseconds that should be skipped forward (positive value given) or backward (negative value given) from the current playback position.
The current implementation in this draft also switches tracks, if the new position is outside of the now playing track (not so useful for podcasts, but useful for audiobooks consisting of multiple tracks). I am not yet settled, if this is the best way to handle it. Another option, i am considering is for the …

Support relative seeking 

---

src/db_init.c
src/db_init.h
src/db_upgrade.c
src/httpd_daap.c

@chme hope to get your opinion on one of the issues with current Apple Music. Its request for playlists looks like this:
`/databases/71/containers?session-id=12345678&revision-number=4&delta=0&query=('dmap.itemname:Library%20name','com.apple.itunes.extended-media-kind:1','com.apple.itunes.extended-media-kind:32','com.apple.itunes.extended-media-kind:128','com.apple.itunes.extended-media-kind:65537')&meta=dmap.itemid,dmap.itemname,dmap.persistentid,dmap.parentcontainerid,com.apple.itunes.is-podcast-playlist,com.apple.itunes.special-playlist,com.apple.itunes.smart-playlist,dmap.haschildcontainers,com.apple.itunes.saved-genius,dmap.objectextradata`
forked-daapd parses that to a SQL query for the playlists table which has a WHERE that includes media_kind. That then fails because there is no …

Make Apple Music on Catalina work

---

src/httpd.c

Fix #814
The problem with the current version of forked-daapd is, that a browser is allowed to keep a cached version of the response for e. g. the `/api/library/playlists` request (`Cache-Control: private`). The browser can use this cached version without checking against the server (forked-daapd) if the cached version is still valid.
This pr solves it by telling the browser that it should always check, if the cached version is still valid. The browser therefor always requests the page from the server and only uses the cached version if the server returns a 403 "not modified" response code.
This obviously results in a lot more requests against forked-daapd while using the web interface. The majority of the requests should be fast, because forked-daapd returns early with a 403 response. …

[httpd] Force browsers to always revalidate their cache

---

.gitignore

Add Eclipse CDT specific files to gitignore
(a new .autotools file was generated by the new Eclipse CDT version)

Add Eclipse CDT specific files to gitignore

---

src/outputs/alsa.c

Typo in cfg - prevents multi ALSA sections from playing

[alsa] cfg section typo using 'mixer_device_name'

---

src/outputs/alsa.c

multi alsa cfg section with no `nickname` will SEGV.  Fix to use name of 'card' when `nickname` not specified.
If we have:
```
alsa "default" {
}
```
This will SEGV at https://github.com/ejurgensen/forked-daapd/blob/cc78926721e991298087a680718e6b5ae1829f27/src/outputs/alsa.c#L1197 because of the definition https://github.com/ejurgensen/forked-daapd/blob/cc78926721e991298087a680718e6b5ae1829f27/src/conffile.c#L128-135  explicitly has
https://github.com/ejurgensen/forked-daapd/blob/cc78926721e991298087a680718e6b5ae1829f27/src/conffile.c#L131 defaulting to `NULL`.
This simple fix forces the `nickname` of the ALSA device to be the same as the `card` name rather than taking a default value which will be confusing if there are multiple `alsa` sections that do not specify a `nickname` - ideally …

[alsa] multi alsa cfg section SEGV with no nickname

---

src/library.c
src/spotify_webapi.c

Fix for this bug https://github.com/ejurgensen/forked-daapd/pull/755#issuecomment-582649979
* spotify `rmetarescan` performs normal `rescan`
* `library` kicks out if mandatory `init` and `metarescan` methods not implemented in `library_source`

Library metarescan fix

---

src/httpd_jsonapi.c

```
==28284== 394 bytes in 2 blocks are definitely lost in loss record 311 of 341
==28284==    at 0x4C2EE3B: malloc (vg_replace_malloc.c:309)
==28284==    by 0xA7B3C89: strdup (in /usr/lib64/libc-2.27.so)
==28284==    by 0x477580: spotifywebapi_access_token_get (spotify_webapi.c:1980)
==28284==    by 0x4494C8: jsonapi_reply_spotify (httpd_jsonapi.c:1110)
```
strdup is never free

Json spotify token leak

---

src/http.c

list is not freed when headers are requested:
```
==17141==    at 0x4C2EE3B: malloc (vg_replace_malloc.c:309)
==17141==    by 0x911DDFE: curl_slist_append (in /usr/lib64/libcurl.so.4.5.0)
==17141==    by 0x44AF19: https_client_request_impl (http.c:379)
==17141==    by 0x470528: request_endpoint (spotify_webapi.c:293)
==17141==    by 0x470648: request_user_info (spotify_webapi.c:339)
==17141==    by 0x470B04: token_refresh (spotify_webapi.c:444)
==17141==    by 0x472E0D: spotifywebapi_access_token_get (spotify_webapi.c:1969)
```
Observed with having spotify enabled at runtime connecting to web i/f.
```
[  LOG]      lib: Library init scan completed in 18 sec (0 changes)
[ INFO]     http: Making request for https://accounts.spotify.com/api/token
[ INFO]     http: Making request for …
```

[http] leak fix for curl_slist_append() 

---

README_JSON_API.md
src/db.c
src/db.h
src/httpd_jsonapi.c

First part to tackle #897, web interface changes will be done in a separate PR.
The changes to the API are backwards compatible, i. e. the `/api/library/playlists` endpoint still lists all playlists (excluding special playlists and folders).
The playlist folder hierarchy can be fetched with the new `/api/library/playlists/{id}/playlists` endpoint.

JSON API - Support for Playlist Folders

---

src/httpd_jsonapi.c
src/remote_pairing.c
src/remote_pairing.h

@ejurgensen This requires a bit more work, but a short test was successful. I am opening the PR early to get feedback, if this change is acceptable. The goal is to be able to call the pairing request with a synchronous command from the JSON API and return a meaningful response (success or failure) to e. g. the web interface.

[pairing] Refactor remote_pairing to use cmdbase

---

README_JSON_API.md
src/db.c
src/db.h
src/httpd_jsonapi.c

Implementing #911 
* New put endpoint `/api/library/playlists/[[:digit:]]+/tracks` to enable `play_count` increment,reset,played.
* re-factored existing `play_count` handling to use one common update function - for future update as per @chme for album updates

[json] enable playlist play_count

---

src/SMARTPL.g

[smartpl] support birate,bits_per_sample,codectype

---

src/library/filescanner_playlist.c

Support `genre` name via m3u `EXTGENRE` [tag](https://en.wikipedia.org/wiki/M3U)
If we have a playlist of internet radio streams, some radio streams show up as `unknown genre` even though they provide some other tags.
```
#EXTGENRE:Internet Radio
http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4extra_mf_p
#EXTINF:-1,RTHK - RTHK Radio 2
#EXTGENRE:Internet Radio
#EXTALB:RTHK Radio Stream
http://stm.rthk.hk/radio2
```

[scan] support EXTGENRE in m3u playlist

---

src/artwork.c

This is a quick, ugly and only partial fix for a problem i am running into.
I have added a podcast stream (https://linuxlads.com/feed_mp3.rss), that does not provide any artwork (at least not at the places forked-daapd currently searches for it). It scans correctly and is shown in the web interface under the podcasts as expected. 
Opening the details dialog for this podcast (podcast album details) now tries to fetch the cover artwork for this podcast. This takes quite a while because it tries to fetch artwork for every podcast episode: 
1. source_item_stream_get
2. source_item_ownpl_get
3. source_item_spotifywebapi_search_get
4. source_item_discogs_get
5. source_item_embedded_get
6. source_item_coverartarchive_get
The resulting "no artwork found" is not cached, i think …

[artwork] Ignore streams with media kind != music in artwork sources

---

forked-daapd.conf.in
src/conffile.c
src/outputs/raop.c

Allow raop control and timing ports to be configured to reduce the number of port needing opening when running behind a firewall and trying to output to airplay devices

[raop] Allow configuration of raop control and timing ports

---

src/outputs/alsa.c

Volume changes to the device don't propagate to the output if the output is idle and the session has closed. This results in the device volume not matching the output volume.

Update volume on device reconnect

---

src/library/rssscanner.c

Prevents a meta refresh (aka web `library rescan`) from resetting `play counts` of RSS podcasts.
Fixes issue when performing an REST `api/rescan` (results in `RSS_SCAN_META` scan type in this module) that would result in a `library_media_save()` -> `db_file_add()` even for entries that already exist in db.  
This would result in dropping db record, incl `play_count` etc instead of an `db_file_update()`.

[library] RSS bug fix - meta rescan resets "play count" and other fields

---

src/outputs/alsa.c

A small PR to aid users in their alsa setup - the server (via optional `audio.list-devices` flag) will log all known h/w and mixer combos that have playback functional and thus values suitable for `audio` section's `card` and `mixer`
```
[  LOG]     main: Forked Media Server taking off
[  LOG]     main: Built with:
[  LOG]     main: - ffmpeg
[  LOG]     main: - iTunes XML
[  LOG]     main: - MPD
[  LOG]     main: - Device verification
[  LOG]     main: - Websockets
[  LOG]     main: - ALSA
[  LOG]     main: - Webinterface
[  LOG]     main: mDNS init
[  LOG]     mdns: Avahi state change: Client running
...
[  LOG]   laudio: Available ALSA devices with playback, card=0 h/w name='hw:0' name=BossDAC:
[  LOG]   laudio:   card='hw:0' mixer='Analogue'
[  LOG]   laudio:   card='hw:0' …
```

[alsa] option to list alsa devices/mixers suitable for playback

---

README_JSON_API.md
src/httpd_jsonapi.c

The new podcast feature requires to identify the RSS playlist for a podcast in order to be able to delete it. Therefor this new endpoint is necessary (and it might be useful for other usecases), that lists the playlists for a given track id.
Here you can find the description of the new endpoint: https://github.com/chme/forked-daapd/blob/jsonapi-track-playlists/README_JSON_API.md#list-playlists-for-a-track
It is a bit incomplete (as mentioned in the description) because it will not list smart playlists that contain this track. But for my needs it is enough :-)

Add JSON API endpoint to fetch playlists for a track

---

src/library/rssscanner.c

I am testing the new RSS feed feature a bit and found this issue with the podcasts i tested with. The metadata tags from the episode streams do contain the podcast author and the podcast title.
The feeds information for title and author are the values shown in other podcast players and they should always hold the correct information. I did not follow the discussion around the PR for the podcast feature, so appologies if this has been discussed already ... (i still think, it is wrong to rely on the episodes stream information ;-)
Podcasts that have this issue are for example:
- https://feeds.lagedernation.org/feeds/ldn-mp3.xml
- https://ubuntupodcast.org/feed/podcast/
(a side effect of this problem is, that the playlist name is not identical to the album name, which makes it sometimes hard …

[rss] Always use RSS feed title and author for album and artist

---

src/library/rssscanner.c

The [RSS spec](https://validator.w3.org/feed/docs/rss2.html) notes of the RSS `elements`:
_All elements of an item are optional, however at least one of title or description must be present_
Protect against junk `pubdate` so we generate using current time - we already have protection for the `element` flds.

[library] RSS - protect against invalid pubdate

---

src/artwork.c
src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/library/rssscanner.c

close #964 
Support RSS podcasts that provide artwork at the feed level rather than embedded in each audio stream.  Solves issue with 0.7 web interface that unconditionally displasy artwork for `now playing` and `album` modals - for RSS streams that provide artwork at feed level, this was a generated image.
* new `artwork_url` column to `playlists` to support _playlist_ wide artwork
* RSS scanner updated to add artwork url from `channel->image->url` if available to `playlist` db entry
* update `artwork` module to consider `artwork_url` if available for `playlitsts`
This PR also deals with the issue observed by @chme in https://github.com/ejurgensen/forked-daapd/pull/953#issuecomment-616042071 where RSS streams have no embedded art in any streams which causes all streams in podcast …

[rss] support playlist wide artwork

---

src/SMARTPL.g
src/SMARTPL2SQL.g

Closes #992 
'random' tag in 'order by' clause to request SQLite to random select data rows from result set
```
"random 3 pop" {
genre is "Pop" and
media_kind is music
order by random desc
limit 3
}
```

[SMARTPL] add 'random' in 'order by' clause

---

src/httpd_dacp.c
src/input.c
src/input.h
src/inputs/pipe.c
src/player.c

Supersedes PR #996 
@uvjustin I am ditching my previous attempt at this, here is another go at it. I wasn't satisfied with Remote and the web not being updated in the same way, so this change has the delayed, async update of db, speakers and clients.
You will see that progress metadata sometimes is slightly delayed compared to the rest. This is because Shairport gives negative playback positions, which forked-daapd interprets as "wait before updating the progress" - and I think that is correct to make the progress match what is actually being played.

Update metadata progress, mk4

---

web-src/src/App.vue
web-src/src/pages/PageAbout.vue

Closes #981 
Uses browser's `navigator.language` string to set locale - `moment` will default to `en-US` (current settings used) is string is not valid/available.
Tested on chrome, firefox on linux and IOS13
---
the `release date` (dd/mm/yyyy) and `added at` (dd month yyyy 24h:mm) are in `en-GB` format rather than default `en-US` format

[web-src] use browser locale for 'time' filter for display

---

Makefile.am
README.md
README_RADIO_STREAMS.md
src/Makefile.am
src/artwork.c
src/artwork.h
src/http.c
src/http.h
src/input.h
src/inputs/file.c
src/inputs/file_http.c
src/inputs/http.c
src/settings.c

@sfeakes here is the change I am planning to better support the StreamUrl tag's, like you proposed. As you can see, in addition to artwork url's it also supports getting track length.
I'm a little unsure what the default behaviour should be. Right now it is to not download the link in the StreamUrl, unless the user has configured forked-daapd with strings to search for. So to use it you need to configure it with the words you want it to search for. This is done via the settings api, instead of config file, because that way it can be changed at runtime, and be made available as a setting via the web interface. Until then, you can do like this to configure it to look for e.g. "url" and "duration" (note that the words also match substrings, so ""duration" is enough to match "eventDuration"): …

[input] Add handler for StreamUrl tag

---

.github/workflows/macos.yml

- fetch raw antlr3 install helper script and make it executable
- fix fatal error "'openssl/ssl.h' file not found" while building forked-daapd (included in libwebsocket.h) (https://github.com/libimobiledevice/libimobiledevice/issues/389#issuecomment-289284190)
A successful run can be found here (before i squashed the commits): https://github.com/chme/forked-daapd/actions/runs/113081141

[gh-actions] Fix OSX build in Github actions

---

src/httpd_streaming.c

If `libav` has no mp3 encode the server does not attempt to send data, but it does not drop the client's connection in `streaming_meta_cb()`
This results in audio packets coming but never sent because of the connected client - we see this in the log:
```
[  LOG]   stream: Will not be able to stream MP3, libav does not support MP3 encoding: 44100/16/2 @ 192000
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
[  LOG]   stream: Streaming unsupported
```
Simple one line fix to drop …

[streaming] bug fix - drop client connections if libav has not mp3 encode 

---

src/httpd_jsonapi.c

Extend `add` endpoint to support SMART query 'limit' directive in `expression` and as `param`
```
curl -X POST "http://localhost:3689/api/queue/items/add?expression=genre+is+%22Pop%22+order+by+time_added+desc+limit+3"
```
or
```
curl -X POST "http://localhost:3689/api/queue/items/add?expression=genre+is+%22Pop%22+order+by+time_added+desc&limit=3"
```

[jsonapi] support 'limit' on 'api/queue/items/add?expression='

---

src/websocket.c

Hopefully fixes #1035 "LWS Ran out of header data space" error seen in the Chrome browser.

[ws] Set websocket header data space

---

src/httpd_jsonapi.c
src/player.c

- If prev command is triggered on the first song in the queue, it will always start the first song from the beginning
- If next command is triggered on the last song in the queue, it will stop playback

[player/jsonapi] Do not report error on skip next/prev if end/start of queue is reached

---

src/outputs/alsa.c

Include ALSA's device name in the ALSA modules 'info' logging to help identify sound devices as seen by the system for assisting config setup
Many configs use ALSA's hw ids to refer to device but ALSA can also use device names:
```
laudio: Available ALSA playback mixer(s) on hw:0 CARD=Intel (HDA Intel): 'Master' 'Headphone' 'Speaker' 'PCM' 'Mic' 'Beep'
laudio: Available ALSA playback mixer(s) on hw:1 CARD=E30 (E30): 'E30 '
```
From the example above can use these ALSA names interchangably:
* `hw:0` and `hw:Intel`
* `hw:1` and `hw:E30`
This is useful to allow configs to refer to ALSA devices rather than card numbers (0, 1, 2..).  This is predominantly useful for USB ALSA devices that may get assigned different ALSA card numbers depending on insert order.

[alsa] dump_card() includes ALSA device name

---

src/library/filescanner.c

Minor fixes:
* `counter` is reset in each iteration of loop over `directories` - this means the _Scanned N files..._ log message can be inaccurate

[scan] files canner minor fixes: bulk_scan() count

---

src/db.c
src/db.h
src/httpd_jsonapi.c

Alternative to #1043
This has the drawback, that the returned media_kind and data_kind are not guaranteed to be the only ones that the tracks for the artist/album have.

Metadata for albums and artists (alternative approach)

---

src/httpd_jsonapi.c
src/spotify_webapi.c

- Adds the missing mapping of the release date during the Spotify scan
- Fixes the release dates beeing off by one day in the JSON API

Map release date for Spotify tracks + fix release data being off by one day

---

src/player.c

The non-timerfd code path depends on SIGALRM being defined, so signal.h always needs to be included.
This allows forked-daapd to build and run on NetBSD and probably other BSD systems too.

Remove unnecessary check for FreeBSD

---

web-src/src/components/ModalDialogPlaylist.vue
web-src/src/pages/PagePlaylist.vue

@chme - Follow up to https://github.com/ejurgensen/forked-daapd/pull/1082#issuecomment-683300664 / bug fix to 0.8.1
The `uris` is passed from `page/PagePlaylist.vue` to handle a dynamic _random_ smartpl playlist - we cannot add via `playlist.uri` because when it will ask the server for that uri it will generate another set of tracks, different to the ones on display of the playlist page

[web-src] random playlist playlist modal fix

---

src/db.c

~~Addresses similar issue as solved by dd811e~~
Newly added/removed playlists are not displayed correctly on web browser if we have already visited `http://localhost:3689/#/playlists/0` ~~as it's cached~~ as the db changes for the playlists are not notified as an event and hence `HTTP_NOTMODIFIED` is returned to browser which uses the cached page.
To reproduce:
* add a new playlist (`m3u` or `smartpl`)
* visit `http://localhost:3689/#/playlists/0` - see new playlist
* remove the newly added playlist
* navigate to `http://localhost:3689/#/music/browse`
* navigate `http://localhost:3689/#/playlists/0` - removed playlist still shown (browser using cached page)
Fix to:
* update `db_statement_run()` to accept and fire events as per `db_query_run()`
* update `db_pl_*()` CRUD functions to notify …

[db] playlist cache invalidation fix

---

forked-daapd.spec.in

Very minor fix to the rpm spec to handle Fedora 33 changing the libplist-devel provides from pkgconfig(libplist) to pkgconfig(libplist-2.0).  All distributions I checked appear to work with BuildRequires of libplist-devel though (but still support the pkgconfig discovery), and it's probably easier than special casing each distribution that changes pkgconfig(libplist) in the future...

[spec] Update rpm spec to handle libplist-devel name variations

---

web-src/src/pages/PagePodcast.vue

@chme - matching this up with `components/ListAlbums.vue`; typo blocks deletion from indidivual `podcast` page.
To reproduce:
* goto any podcast page via `http://localhost:3689/#/podcasts`
* click elipisis to bring up dialog
* click `Remove Podcast` - no subsequent dialog box pops up to initiate the deletion

[web-src] typo blocking podcast deletion dialog

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml

Exclude compiled Javascript files from the (Javascript) CodeQL scanning.

[gh-actions] Add codeql config file to exclude compiled js, html, css

---

README_ALSA.md

There is a small typo in README_ALSA.md.
Should read `volume` rather than `volumne`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, volumne -> volume

---

src/httpd_jsonapi.c
src/library.c
src/library.h

Using the (default) delayed update trigger for adding podcasts to the library causes problems, if a JSON API client directly tries to reload the podcasts list after the (synchronous) call to add a new one returns. Instead of using the delayed update trigger, take care of notifying and updating the db timestamps (for cache invalidation) in the `librariy.c` `item_add` function.
Should fix #1132

[library] Directly notify listeners of db changes after adding new items

---

src/db_upgrade.c

The break results in the ugrade stopping at v2103 and only after another
restart of forked-daapd the update to v2104 happens. Removing it will
directly update to the latest DB version.

[db] Remove break after v2103 db update and directly run update for v2104

---

src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/httpd_jsonapi.c
src/library/filescanner.c
src/library/filescanner_smartpl.c
src/player.c
src/spotify_webapi.c

@chme in this PR I have made some changes so that the queue functions in db.c are more similar to the functions for files and playlists. As part of that, adding and updating queue items now use prepared statements. I also tried to consolidate the mapping of fields between mfi/dbmfi and queue items into a single table.
While testing this I came across an issue that I would like your view on. It relates to the query_limit of playlists, where I saw that in my database there are no less than three different default values used: -1, 0 and UINT32_MAX. The -1 comes from your PR #525 (specifically commit 6ceede44f49cb0c9500069b1844c2322205ea529), and the UINT32_MAX is a result of my later implementation of prepared statements, where bind_generic() casts pli->query_limit to uint32_t when saving to …

[db] Prepared statements for queue items + some refactoring

---

src/library/filescanner.c
src/library/filescanner.h

Now that the iTunes configuration option was removed in a5bd8b011e6aaa7c565939525592c11a1d235a9e, remove leftover `#ifdef`s that exclude the iTunes scanning implementation.

[scan] Remove leftover iTunes #ifdefs

---

.github/workflows/codeql-analysis.yml
.github/workflows/ubuntu.yml

These changes hopefully help us detect more errors automatically by gh-actions:
- in code ql analysis build with scan-build to detect errors and build with additional dependencies to cover more code in forked-daapd
- in code ql analysis remove the special git checkout command due to the warning from code ql action (e. g. https://github.com/ejurgensen/forked-daapd/actions/runs/651612902)
- in ubuntu add additional step to build with optional dependencies to cover more code
We don't have 100% coverage of our code, e. g. scan-build with pulse audio or building with spotify. I am not sure if we should add them.
ref: https://github.com/ejurgensen/forked-daapd/pull/1209#issuecomment-799758597

[gh-actions] Add scan-build and build for more configurations

---

README_JSON_API.md
src/httpd_jsonapi.c

@cdlenfert this should make it possible to get the info with just one request. If you can test it is of course good, but it's a simple change, so I expect to merge it even if you can't.
Closes #1206

[jsonapi] Get currently playing queue item details

---

src/outputs/pulse.c

I'm using Pulseaudio output with a speaker and a bluetooth headset. Sometimes when I turn of the bluetooth headset Pulseaudio creates an error and then the sinklist callback is called with a nullptr information structure. According to the [Pulseaudio documentation](https://freedesktop.org/software/pulseaudio/doxygen/introspect.html) this is valid call, and with this fix everything work as expected, even if the callback is called with a nullptr.

Fixed potential crash on pulseaudio sink info callback, when an error occurs

---

src/library/filescanner_ffmpeg.c

In the case of ALAC files, the name of the sort tags was reported by ffmpeg with a different name than the others.
I checked the ffmpeg source code and added the missing names.
https://github.com/FFmpeg/FFmpeg/blob/n4.4/libavformat/mov.c#L350
This is my first pull request, so please let me know if there are any mistakes.

[scan]Add sort tags for ALAC

---

configure.ac
src/websocket.c
web-src/src/App.vue

I use the JSON API to be informed about player states to power a connected amplifier. Unfortunately, the events for this often come very delayed (up to 10 seconds, even in the web interface the player state updates are usually updated much later). The problem seems to be that in libwebsockets 3.2 the function `lws_service()` has been changed, the timeout parameter is now ignored and thus the event callback is obviously scheduled after the next communication. However, version 3.0 also brings a nice change that makes it possible to schedule events from another thread. This pull-request switches to this new scheduling model. The clients now only get the events they have requested, this is the reason why the web interface now also requests the `queue` event. Also a race-condition when …

Improve the websocket to send events to clients immediately.

---

owntone.service.in

Particularly avahi-daemon is a pretty hard requirement of owntone; currently it's expected that the user has started/enabled the service rather than directly depending on it.

Add additional dependencies for systemd startup.

---

src/db.c
src/library/filescanner.c
src/spotify_webapi.c

Caused by queue_item_add returning >0 as success, but calling function is expecting ==0.
This change also tries to avoid other/future occurences of this issue by generally checking for error ("ret < 0") instead.

[db] Fix error where adding e.g. Spotify track to queue returns "0 tracks added"

---

README_JSON_API.md
README_SMARTPL.md
src/SMARTPL.g
src/httpd_jsonapi.c

Fix #1213 by adding the "comment" field to the smart playlist expression language. The "comment" field is additionally exposed in the JSON API.

[smartpl] Add "comment" field to smartpl expression language

---

INSTALL.md
Makefile.am
configure.ac
scripts/freebsd_install.sh

Easier install by letting 'make install' add user and service files
If --enable-install-user set add owntone system user and group (unless other user/group specified with --with-user or --with-group). The user will be added to pulse-access if the group is present.
Don't overwrite config, it's a pita. Use same solution as shairport-sync where distros can use --disable-install_conf_file if required.
A './configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var' will result in service files in /etc/systemd/system, which seems sensible. Package builds can specify other location, e.g. --with-systemdir=/lib/systemd/system, or ship their own service file and use --disable-install-systemd.
Also added more cleanup on uninstall - before we where leaving stuff in /var/cache/owntone + the logs …

Easier installation

---

src/httpd_jsonapi.c
src/inputs/spotify.c
src/inputs/spotify.h
src/inputs/spotify_librespotc.c
src/inputs/spotify_libspotify.c
src/library/spotify_webapi.c

This PR implements scanning saved Spotify podcasts (shows) into the library (fixes #1274).
Spotify podcasts require the new Spotify input implementation.
@ejurgensen I added a flag to `spotify_backend` struct that indicates if the input spotify implementation supports playing podcasts. Please let me know if there is a better way to get this information.
There is room for improvements:
- ~~Artwork is not displayed for shows/episodes~~
- Information if an episode has been fully played is not mapped into our library (same applies for resume point)
- Show and episode descriptions are not mapped into our library
- Through the OwnTone Web API it is not possible to play a show/episode that is not scanned into the library
- Spotify search results for in the web interface for shows/episodes would …

[spotify] Scan spotify podcast subscriptions into library

---

README_JSON_API.md
src/SMARTPL.g
src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/httpd_jsonapi.c

implements https://github.com/owntone/owntone-server/issues/1306
Add `flag` to `files` and `queue` tables to support user _marking_ of tracks for the purpose of maintanence/review (outside of the server).
For instance, user adds many tracks to server without reviewing tracks but may find that they don't like and wish to remove; in normal situation user would need to note the track, find the corresponding file in library and then detele.  Having a flag in db that marks a track (for future implementation in web ui in `now playing` page/modal) for review helps automate this use case.
Tracks are marked via `PUT` on `http://<server>:3689/api/library/tracks/1234?flag=1`
Tracks are identified via `GET` on `http://<server>:3689/api/search/type=tracks&expression=review+>+0` which will provide the …

[db] add 'flag' to files and queue tables

---

owntone.spec.in

This PR gets the SPEC file to work properly with the release tarball.  Specifically, I needed to:
* Change the Source tarball from GZ to XZ
* always depend on protobuf-c (configure exits if it's not found, even without chromecast)
* the build system installed owntone.service into /etc, which is wrong.  Exclude that location and use the correct location.
With these changes, the RPM builds on FC35.

Get SPEC file to build with 28.2 and FC35

---

INSTALL.md
Makefile.am
README.md
owntone.spec.in
owntone@.service.in

This PR adds a systemd template service that gets installed along with the standard service unit.  It includes that template service in the RPM file, and updates the documentation (INSTALL.md) to describe, minimally, how to use it.
This is a primary approach to handle Issue #1189, although it would be best to be able to do it all from a single instance so you wouldn't have the potential to try to send two audio streams to one output (which doesn't work for obvious reasons).

Add a SystemD template service for owntone

---

src/outputs/airplay.c
src/outputs/raop.c
src/pair_ap/pair-internal.h
src/pair_ap/pair.c
src/pair_ap/pair.h
src/pair_ap/pair_fruit.c
src/pair_ap/pair_homekit.c

Update pair_ap to version 0.11, which it fixes an issue where some randomized values of SRP "a" are short enough that they require padding.

Update pair_ap to version 0.11

---

src/conffile.c
src/http.c

This solves for the case where hosted RSS podcasts have self signed or expired certs:  using default (verify peer) in these instances results in a `libcurl` error: `SSL peer certificate or SSH remote key was not OK`.
This also appears to be a libcurl version issue - running on this on Fedora 35 I don't get this problem with the master branch, running against libcurl 7.79.1 but this problem does appears on my RPi1 running `buster` with libcurl 7.64
```
$ ldd /usr/sbin/owntone | grep curl
libcurl-gnutls.so.4 => /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4 (0xb5496000)
$ dpkg -S /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
libcurl3-gnutls:armhf: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4
$ $ apt show libcurl3-gnutls:armhf
Package: libcurl3-gnutls
Version: 7.64.0-4
```
By …

[http,conf] allow user to request no ssl peer verification

---

web-src/src/components/ListAlbums.vue

On the `podcast` page, when you mark a podcast as played (using the album modal) the unplayed tracks for that RSS, on the podcast page, are not updated because there is a missing propogation of the `play_count_changed` event.
* elipsis on CGP Grey podcast, "mark as played"
* the podcast episodes at the top of screen for podcast should disappear
* currently they don't due to the missing event propogation
Simply fix to propogate
cc @chme

[web-src] podcast handling of propogated 'play_count_changed' event

---

README.md

README.md update to clarify that the MP3 stream icon starts background playing.

Use of MP3 stream icon in speaker selection

---

README_JSON_API.md
src/artwork.c
src/db.c
src/db.h
src/httpd_daap.c
src/httpd_dacp.c
src/httpd_jsonapi.c
src/httpd_rsp.c
src/inputs/pipe.c
src/library/filescanner.c
src/library/filescanner_itunes.c
src/library/filescanner_playlist.c
src/library/rssscanner.c
src/library/spotify_webapi.c
src/mpd.c

@ejurgensen I had a look at #1335 and I don't think adding additional methods to fetch the composer is a good idea. An alternative solution could be to extend the existing browse queries to include the additional meta data. This has the benefit, that the genre queries now also are able to fetch track count, artist count, etc.
This PR adds a "db_browse_info" struct and maps the now available meta data for genres in the JSON API.
While copy & pasting the code from the existing fetch-query-functions, I thought it would be good to refactor the logic into a generic function. The last commit in this PR does this refactoring. The refactoring is not done yet, especially changing the return value requires additional changes. This is why this PR is a draft. 
What do you think, is the refactoring …

Fetch additional meta data in "browse" queries

---

src/httpd_jsonapi.c
web-src/src/components/ListComposers.vue
web-src/src/components/ListItemComposer.vue
web-src/src/components/ModalDialogComposer.vue
web-src/src/components/TabsMusic.vue
web-src/src/lib/Composers.js
web-src/src/pages/PageComposer.vue
web-src/src/pages/PageComposerTracks.vue
web-src/src/pages/PageComposers.vue
web-src/src/pages/PageSearch.vue
web-src/src/router/index.js
web-src/src/webapi/index.js

Implements #1331 
Adds support for `composer`:
* update `pages` akin to `artist`
* update search to incl `composers` in search results
* add to tabs (like `genre`) so will list all `compsoers`
cc: @chme

[web-src] add composer support

---

src/db.c
src/db.h
src/db_init.c
src/db_init.h
src/db_upgrade.c
src/httpd_jsonapi.c
src/library.c
src/library.h
src/library/filescanner.c
src/library/filescanner_playlist.c
src/library/rssscanner.c
src/library/spotify_webapi.c
src/mpd.c

This PR implements a generic approach to trigger a library update for a single library source.
Usecases are updating only the Spotify library or updating the podcasts RSS feeds (alternative solution to #1323).
- The JSON API endpoints to trigger a library update now take an optional query parameter `source`) 
- The JSON API endpoint to fetch library information (`GET api/library`) now returns an additional attribute `sources` that list the available library sources
- Includes a DB update to DB version 21.08 (add new column `source` to files, playlists and directories table)
- Each library entry for files, playlists and directories now has a reference to the library source that created it / is responsible for it.
This PR does not include the web interface changes.
This PR requires more …

Add "source" field to db and add support to update a single library source

---

sqlext/Makefile.am
sqlext/sqlext.c
src/db.c

E.g.:
- 'é' LIKE 'e'
- 'æ' LIKE 'Æ'
- 'Ö' LIKE 'o'
Based on sqlite's icu.c and fts5_unicode.c

[db] Improve search by supporting diacritics and Unicode case folding

---

src/httpd_streaming.c

[streaming] memleak introduced via e1375f6ad

---

src/httpd.c
src/httpd.h
src/httpd_jsonapi.c

This PR refactors the endpoints for genres and composers to use a common generic "browse" endpoint.
The endpoint urls for clients (e. g. the web interface) do not change, the change is only internal in the httpd_jsonapi (reduce code duplication).
An additional new generic "browse item" endpoint is also introduced, to fetch info for a specific genre/composer (similar to artist or album). I want to use this in the web interface to fix a minor inconsistency between the compose/genre and e. g. artist views.

[jsonapi] Generic browse endpoints

---

src/db.c
src/library/spotify_webapi.c

@ejurgensen @ben-willmore This PR should fix #1426 
I only did a short test ... would be great if you could test if it works for you.
@ejurgensen I noticed that the "artist_override" did still not work after the fix in `spotify_webapi.c`. The problem is, that the during the scan, the compilation flag did not result in setting the album artist to the configured compilation artist. This also effects local files stored in the compilation folder. My guess is, that the behavior broke with the change to prepared statements for track inserts. I fixed this with e5d3c148ea7f11b5c40ab555ef36b3ae552973a0 (in this PR). Please take a closer look at this commit.

Fix for Spotify config option album_override has no effect

---

src/websocket.c

Closes #1423
Cancels the websocket service in deinit for faster thread exit instead of waiting for weboskcet internal loop to timeout

[web] slow 4.1.6 shutdown; request to cancel ws loop

---

src/httpd_jsonapi.c

This additional information allows to filter playlists that only contain streams in the web interface (see #1107).
I chose to not do this directly in the playlists endpoint. The filtering would need to take place after fetching the playlists from the DB and that makes it hard to implement the paging functionality that the playlist endpoints support.
The actual filtering of radio only playlists will be done in a separate PR.

[jsonapi] Add item and stream count to playlists, expose config option "radio_playlists"

---

src/outputs/rcp.c

the `rcp_session_cleanup()` advances the head of sessions list so no need to do again in deinit loop

[rcp] bug fix on deinit() 

---

src/artwork.c
src/http.c
src/http.h
src/inputs/http.c
src/inputs/spotify_librespotc.c
src/lastfm.c
src/library/rssscanner.c
src/library/spotify_webapi.c

My Spotify library is getting larger and it takes now a significant amount of time to run the spotify library scan ...
One way I found to improve it is to reuse the curl handle. Reusing the handle - instead of creating a new one for each request - will keep the connections, session ID cache, DNS cache and cookies.
The implementation in this PR is a proof of concept.
Some "benchmarks" from my raspberry pi 3B:
Without reusing the curl handle (current master branch):
```
[2022-04-17 10:19:28] [  LOG]  spotify: Spotify scan completed in 313 sec
[2022-04-17 10:52:57] [  LOG]  spotify: Spotify scan completed in 212 sec
[2022-04-17 10:57:36] [  LOG]  spotify: Spotify scan completed in 248 sec
```
With reusing the curl handle (this PR branch):
```
[2022-04-17 11:10:09] [  LOG]  spotify: Spotify …
```

[http/spotify] Allow reuse of curl handle to improve Spotify scan performance

---

src/player.c

Without this the web ui does not know that an output device failing, volume/selected status remains.
```
[2022-04-29 21:56:10] [ INFO]      rcp: Connection to 'RCP/SoundBridge Test Harness' established
[2022-04-29 21:56:11] [ INFO]      rcp: Ready 'RCP/SoundBridge Test Harness' volume at 23
*** kill the Roku
[2022-04-29 21:56:15] [  LOG]      rcp: Failed to read response from 'RCP/SoundBridge Test Harness' - Connection reset by peer
[2022-04-29 21:56:15] [  LOG]      rcp: Failed to recv/construct response from 'RCP/SoundBridge Test Harness'
[2022-04-29 21:56:15] [ INFO]      rcp: Disconnected 'RCP/SoundBridge Test Harness'
[2022-04-29 21:56:15] [ WARN]   player: The RCP/SoundBridge device 'RCP/SoundBridge Test Harness' failed
```
Without change, at the webui's speakers still show the Roku …

[player] send volume event when a device fails

---

src/outputs/rcp.c

Two bugs:
- ensure device flag is `selected = 0` to reflect unconnected status (must initiate Soundbridge connection by design)
- sync volume of Soundbridge to last known volume as set by server
trying to fetch volume of soundbridge (which might have changed since last use by server) proving problematic and volume not reflecting correctly on web ui

[rcp] bug fix - speaker unselection upon restart / obey volume 

---

src/mdns_avahi.c

mdns_init: avoid null reference access
- when avahi client creation fails with mdns_client=null, use `avahi_strerror(error)` instead of `MDNSERR`  to avoid access to `mdns_client->error`.
While testing owntone for synology NAS (https://github.com/SynoCommunity/spksrc/pull/4337) I got an assertion
`owntone: client.c:791: avahi_client_errno: Assertion 'client' failed.`
With this fix I get the correct error message:
`[2022-05-22 20:22:22] [ WARN]     mdns: mdns_init: Could not create Avahi client: Daemon not running`
This does not solve my problem, that no mdns service is running.
Any hint for what I might be missing?

mdns_init: improve error handling (avoid null reference access)

---

src/httpd_jsonapi.c
src/library/spotify_webapi.c
src/library/spotify_webapi.h
web-src/src/pages/SettingsPageArtwork.vue
web-src/src/pages/SettingsPageOnlineServices.vue

@ejurgensen I have removed the libspotify special handling from the web ui (and also removed some left overs from the JSON API). In `spotify_webapi.c` some additional methods are now unused (they were only used by libspotify) and have been removed.
Maybe a bit controversial could be a commit I added to this PR that removes the creation of the special playlist "Spotify saved".
For some time now, the special playlist is not used any more by the (re)scan to avoid purging saved albums.
I don't see the need to keep it, at least to some extent it could be replaced with a smart playlist.
But if you think, it is worth keeping it, I will drop the commit from this PR.

Some additional cleanup after the libspotify removal

---

src/httpd_dacp.c

IOS remote - Playback does not start when user selects a track on the "up next" screen when server is stopped/restarted.
To reproduce:
* stop player or restart server 
* clear Q
* adds items to Q using 'add next'
* select item on 'up next'
Error reported:
```
[DEBUG]     dacp: DACP request: '/ctrl-int/1/playqueue-edit?command=playnow&index=1&session-id=886488353'
[DEBUG]       db: Fetch by pos: pos (0) relative to item with id (0)
[DEBUG]       db: Running query 'BEGIN TRANSACTION;'
[DEBUG]       db: Fetch by pos: pos (0) relative to item with id (0)
[DEBUG]       db: Running query 'SELECT pos FROM queue WHERE id = 0;'
[ INFO]       db: No matching row found for query: SELECT pos FROM queue WHERE id = 0;
[DEBUG]       db: Running query 'END TRANSACTION;'
[  LOG]       db: Error fetching …
```

[dacp] play item from 'up next' when stopped

---

configure.ac
src/library/filescanner_ffmpeg.c
src/transcode.c

@whatdoineed2do your PR #1536 had me look at transcode.c, and that triggered a few things I would like to change:
- Drop asking decoder for specific sample formats/channels, let the filters take care of that (I think requesting this from the decoder predates using filters and isn’t necessary any more).
- Alignment of how ffmpeg API version switches are done.
- A bit of refactoring of the wav header function.
I also got to test some more, and I see that your original check for AV_CHANNEL_ORDER_UNSPEC is better than the use of av_channel_layout_check() that I suggested. I have an AIF test file where ffmpeg doesn’t return a stereo channel layout, but AV_CHANNEL_ORDER_UNSPEC and two channels. av_channel_layout_check() will say that is ok, but it won’t work as channel layout input to the …

Adjustments to ffmpeg/transcoding

---

src/db.c
src/db.h
src/httpd_jsonapi.c
src/library/filescanner_ffmpeg.c

Closes #1555
Release date of track is assumed to be >1970 and stored/handled as an `uint32_t` which causes mishandling of dates before unix epoch.  For example, a file with release date of `1960-10-04`, the db stores `date_released` as `4003280896` vs `-291686400` and gets misidenfied as a date in 2096.
I've bumped the storage and handling of `struct media_file_info::date_released` to `int64` since there's a note for all ints to be handled as unsigned. 
Test before and after through json api  (see `date_released`):
* master
```
{
"id": 47,
"title": "old song",
"title_sort": "old song",
"artist": "foobar",
"artist_sort": "foobar",
"album": "nothing good",
"album_sort": "nothing good",
"album_id": "2347841309122213946",
"album_artist": "foobar",
"album_artist_sort": "foobar", …
```

[db,scan,jsonapi] bug fix to handle date_released before 1970

---

web-src/index.html
web-src/package.json

cc: @chme 
We can reverse proxy `owntone` by following instructions on the wiki:
https://github.com/owntone/owntone-server/wiki/Creating-a-reverse-proxy-using-NGINX.
but the `index.html` and `vite` generation forces the proxy address be at `/` which is not ideal:  simple change to allow proxying from any subdir:
```
#/etc/nginx.conf
...
http {
server {
...
location /daap/ {
proxy_pass http://127.0.0.1:3689/;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}
}
}
```

[web-src] fix to allow reverse proxy from subdirs

---

web-src/src/locales/de.json
web-src/src/locales/en.json
web-src/src/locales/fr.json

In the current version 28.6, there are a few missing translations in French and English.
This is mainly to the addition of the German language, which was not added in French and German.
Moreover, there were a few missing translations in French and some typos that have been corrected along the way.
It could be great if these minor amendments could be integrated into the next release.
Thanks a lot.

I18n: Correction of translations in French, German, and English

---

web-src/src/App.vue

When the connection with the OwnTone server is lost, the error message is not displayed.

Error message not displayed

---

src/mdns_avahi.c

This pull request addresses a somewhat obscure issue where ipv4 A records are published over the ipv6 network.
The MDNS spec allows publishers to publish A records and AAAA records over either ipv4 or ipv6 or both networks. This rarely presents an issue, since most mixed ipv4/ipv6 publishers will publish both A records and AAAA records on both networks, and clients can find whichever one they prefer. In some unusual circumstances, an ipv4 only publisher's ipv4 A record may be broadcast (or received) only over the ipv6 network.
The specific circumstances I am dealing with where this arose is as follows. I recently decided to segregate my iot devices into a separate vlan. This included one of my airplay players -- an old Apple AirPort Express. I also set up my router, a Ubiquiti EdgeRouter …

Allow mixed ipv4/ipv6 mdns

---

src/mpd.c

Fixes https://github.com/owntone/owntone-server/issues/1613 by replacing newline character with a space.

[MPD]: sanitize newline characters in ID3 tag values

---

src/mdns_avahi.c

As reported in issue #1654, using select to test for a (non-blocking) connection success crashes on FreeBSD when the number of opened file descriptor is higher than FDSET_SIZE. 
Instead of returning with an error in that case (and skipping the connection test), this commit uses poll instead that's not limited to the number of opened file descriptors, preventing an out-of-bound write.
Fix #1654

Fix select issue on FreeBSD.

---

.github/workflows/build_htdocs.yml
.github/workflows/codeql-analysis.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml

@hacketiwack I think it would be good if Github actions was used to automatically rebuild the web UI whenever a change is pushed to web-src. Thus, there is no relying on the build on a local machine, and the rebuilt UI can be kept out of a PR.
Let me know if you have any concerns about this.

Let Github actions rebuild web UI on push to web-src

---

web-src/src/components/LyricsPane.vue

There's a bug in the lyrics pane being sometime too big for the covert art underneath.
This happens when the album art aspect ratio is inverted (portrait instead of landscape). Since only one dimension is specified for the image, the other dimension is computed from the aspect ratio. 
Most of the time, the covert is in landscape mode, so the height is what set in the `max-height` property, but when it's in portrait, the max-height property isn't used and the height is smaller.
This changes account for the 2 cases and select the minimum dimension (so the lyrics should never override the time slider).
This fix #1689's remark that I've observed.

[web] Various CSS fixes

---

docs/json-api.md

Owntone server supports the `composer` result type instead of `genre` type, I think.
What do you think?
The implementation of search term is here:
https://github.com/owntone/owntone-server/blob/master/src/httpd_jsonapi.c#L4444

[docs] Fix the result types in "Search by search term"

---

.github/workflows/codeql-analysis.yml

As the version 2 of the GitHub action for CodeQL is deprecated and will be removed at the end of the year (2024), the newer version (3) should be used instead.
More information [here](https://github.com/github/codeql-action).

[workflow] Upgrade GitHub actions to newer versions

---

.github/workflows/codeql-analysis.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
configure.ac
docs/building.md
owntone.spec.in
scripts/freebsd_install.sh
src/httpd_rsp.c
src/misc_xml.c
src/misc_xml.h

mxml 4 is binary and source incompatible with 3, and there is no easy way to stay compatible with both. Not great for a library. So replace with libxml2, hopefully that is more stable. Also means we can get rid of all the mxml hacks.

Switch from mxml to libxml2

---

owntone.conf.in
src/conffile.c
src/mpd.c

MPD produces the following entry on outputs command:
OK MPD 0.23.5
outputs
outputid: 0
outputname: MP3 stream
plugin: httpd
outputenabled: 1
OK
This indicates to some clients that a HTTP stream is available, and without it they will refuse to do any config/support for it (if at all). While this stream normally would be available on port 8000 that is something that can easily be directed to stream.mp3 using a proxy in front.
Faking this "plugin" simply allows some client to make use of owntone's http stream.

mpd: mimick httpd plugin as output

---

src/mpd.c

Maintain the binary limit, and use the default MPD uses too.  This comes in handy when we are going to send binary responses such as in PR#1780

[mpd] add binarylimit command (still unused)

---

src/mpd.c

This key confuses some clients, and it isn't emitted by MPD, nor documented to exist:
https://github.com/MusicPlayerDaemon/MPD/blob/9ff8e02e543ede2b1964e5ea3f26f00bf2ff90ec/src/output/Print.cxx
It was added in bdb2c7493, but without explanation why it was added to outputs command.

[mpd] outputs: drop invalid outputsvolume key

---

docs/configuration.md

Updating the documentation following the deprecation of `cache_path` in version 28.10.

[docs] Change cache_path to cache_dir

---

owntone.spec.in

The rpm spec file contains a BuildRequires of pkgconfig(libxml2), but the libxml2-devel package has a Provides of pkgconfig(libxml-2.0)
This patch to spec file to update the BuildRequires to use that value.

Correct libxml2 BuildRequires in spec file

---

web-src/src/pages/PageNowPlaying.vue

I noticed, that when you are on the "now playing" page in the web interface and hit the pause button, the track progress bar keeps updating.
After debugging it, this happens because the "watch" for "playerStore" is never triggered. Watching only the "state" property instead of the whole store object, fixes it - though I am not sure why watching the store does not work in the first place ...

fix: Now Playing does not stop play progress updates when pausing

---

.clang-format
.dev/Makefile
.dev/devcontainer/.scripts/init-devcontainer-cli.sh
.dev/devcontainer/.scripts/install-devcontainer-tools.sh
.dev/devcontainer/data/devcontainer-owntone.conf
.dev/devcontainer/devcontainer.env
.dev/devcontainer/ubuntu/Dockerfile
.dev/devcontainer/ubuntu/devcontainer.json
.dev/vscode/c_cpp_properties.json
.dev/vscode/launch.json
.dev/vscode/settings.json
.dev/vscode/tasks.json
.gitignore
docs/development.md
mkdocs.yml
src/db.c
src/db.h
src/main.c
web-src/package.json

This PR aims at making the set up of a new development environment for OwnTone a bit easier for newcomers by offering near automatic set up for VSCode with the help of [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers).
Setting up a development environment for OwnTone is not a trivial task. To get everything working from the C compiler chain, the dependencies, the web interface and building the documentation, requires a lot of knowledge which tools have to be installed etc. There exists already a lot of documentation (from the docs to the container files or the github yaml files), but you have to dig a bit through the different sources to get everything working.
With this PR, to set up a fully working environment it should be enough to:
- copy ` .dev/vscode` to …

dev: Add template for VSCode settings and devcontainers

---

configure.ac

During configuration (`autoreconf`) step of the make process, some warnings are displayed, as depicted below.
```log
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:34: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
./lib/autoconf/programs.m4:716: _AC_PROG_LEX is expanded from...
./lib/autoconf/programs.m4:709: AC_PROG_LEX is expanded from...
aclocal.m4:3686: AM_PROG_LEX is expanded from...
m4/ax_prog_flex.m4:47: …
```

[configure] Fix AC_TRY_LINK warning

---

owntone.8
src/Makefile.am
src/db.h
src/http.h
src/httpd.c
src/httpd_jsonapi.c
src/lastfm.c
src/listenbrainz.c
src/listenbrainz.h
src/logger.c
src/logger.h
src/main.c
src/player.c

This PR adds support for submitting "listens" (played songs) to ListenBrainz (<https://listenbrainz.org>).
ListenBrainz offers similar functionality as Last.fm, but the data is open (see their [About page](https://listenbrainz.org/about/) for their stated goals).
Integration of ListenBrainz in OwnTone would allow users to use ListenBrainz to keep a (public) listening history instead of using the proprietary Last.fm service.
This PR implements:
- Support submitting listens (scrobble) to ListenBrainz.
- Add JSON API endpoints to manage ListenBrainz auth token.
Note, that a minor refactoring was done in cc0d2ff985e0ec00dbc979278fc037cf271380ab.
I am opening this as draft, to see if there is interest in adding this functionality to OwnTone. And if yes, if the approach is OK.
Open topics to …

feat: Support scrobbling played songs to ListenBrainz  

---

web-src/src/stores/configuration.js

Added the 2 missing config fields to the configurationStore. On v28.11, the absence of these 2 fields was preventing the queue save as playlist button from appearing, even though the /config endpoint was returning the right fields.
Verified by editing the compiled Vue index.js to add these 2 fields: after that the save button appeared in the Queue page.

[web] Add missing fields to configuration store

---

src/httpd_jsonapi.c

This change allows stopping the playback once the last item is removed from the queue.
It is a fix for the open reported bug [1581](https://github.com/owntone/owntone-server/issues/1851).

[api] Stop playback once last item is removed from the queue

---

configure.ac
src/db.c
src/httpd.c
src/logger.c
src/misc.c
src/misc.h

Given that owntone is multi threaded, adding the info to which thread a log message belongs to, makes it much easier to analyze the logs.
I also find it helpful, to see, which threads are notified in the `unlock_notify_cb`.  
I added logging of the thread name and id unconditionally. It would also be possible to add a command line argument or a compile time/configure flag, to make it conditionally.
Example log with thread name and tid:
```
[2025-02-16 05:37:11] [DEBUG] [owntone (6360)      ]       db: Running query 'PRAGMA synchronous;'
[2025-02-16 05:37:11] [DEBUG] [owntone (6360)      ]       db: Database synchronous: 1
[2025-02-16 05:37:11] [ INFO] [owntone (6334)      ]    cache: Cache thread init
[2025-02-16 05:37:11] [  LOG] [cache (6361)        ]    cache: Could not open …
```

[logger] Log thread name and id

---

src/library/spotify_webapi.c

I ran into a deadlock between the library thread and a worker thread for an artwork request. The deadlock occurs when the library thread does the Spotify scan and an artwork request is made. 
- During the scan, the library thread holds the lock on the spotify credential mutex. 
- When there is an artwork request in parallel (e. g. opening the albums page in the web UI), this request is processed in one of the worker threads. Finding artwork opens a DB query to fetch the files (in `process_items`) and steps over the result set. This results in a DB lock held until the query is finalized.
- The Spotify artwork source now tries to find the artwork in Spotify and blocks because the library thread still holds the lock on the credential mutex. 
- During the scan in the library thread, it want's …

[spotify] Fix possible deadlock during Spotify scan

---

src/conffile.c
src/logger.c
src/logger.h
src/main.c

Especially with debug or spam logging enabled, it is difficult to spot warnings or errors in the log file. It would be nice, if owntone would support structured logging get the most out of existing logging tools out of the box.
With this PR, I propose to add support for the [logfmt](https://brandur.org/logfmt) log format. 
In my opinion, logfmt has a good balance between being human and machine readable. And a lot of tools have support for it. I like for example [hl](https://github.com/pamburus/hl), a terminal log viewer with formatting and filtering.
Example log:
```
time=2025-02-23T16:29:48+0100 level=LOG thread="owntone (6128)" component=main msg="OwnTone version 28.12 taking off "
time=2025-02-23T16:29:48+0100 level=LOG thread="owntone (6128)" component=main msg="Built with: " …
```

[logger] Add support for structured logging ("logfmt" format)

---

.github/workflows/macos.yml

The macros shipped with Homebrew's gettext are no longer installed to $(brew --prefix)/share/aclocal, so aclocal can't find them, resulting in autoreconf failing.
Fixes issue #1889

[gha] Fix MacOS workflows failing with undefined macro errors mk2

---

docs/advanced/remote-access.md

Just having the `"ffid=..."` argument doesn't seem to be enough to make the owntone library appear in recent versions of Apple's Music.app; I copied the extra arguments from a real instance of Music.app and with them, the owntone library is usable in Music.app like it used to work in iTunes.

Update dns-sd arguments for modern Apple Music app

---

web-src/src/components/ModalDialog.vue

On mobile the modal dialogs for albums do not show the action buttons (play, add, ...) any more.
It seems, that Bulma calculates the height of the `modal-content` differently then it did before. Because of that, the value for `max-height` of `card-content` in `ModalDialog.vue` is too high. On mobile viewport this leads to the `content-footer` being rendered outside of `modal-content`.
The `max-height` of `modal-content` is `calc(100vh - var(--bulma-modal-content-spacing-tablet))` on tablet viewport. Subtracting the previous value from it, makes the action buttons visible on mobile again.
Not sure if there is a more elegant approach ...

[web] Fix modal hight to display buttons on mobile
